import React, { useEffect } from "react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import Notice from '@/components/Notice'
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import about from '@/img/about-hello.svg'
import sumail from "@/img/sumail.jpg";
import mathew from "@/img/mathew.jpg";

export default function About() {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <Notice />

        <div className="h-max flex py-12 px-20 bg-[#f2f2f2]">
          <div className="flex flex-col mx-auto space-y-6 justify-center2 items-center">
            <div className="flex space-x-6 items-center">
                <div>
                    <Image src={about} alt="" />
                </div>
                <span className="text-5xl font-mabrybold leading-tight text-indigo-700">
                We make Glitch so it's easier for you to make the web.
                </span>
            </div>
            <div className="text-2xl font-mabry leading-relaxed">
                <p className="py-3">
                Glitch is the place where millions of creators, professionals and educators build the open web together. Our job is to give you fast, fun tools for building the website of your dreams.
                </p>
                <p className="py-3">
                We make it easy to instantly remix projects and put your own spin on them. Just start typing, and Glitch will immediately show your changes in a preview window. Glitch began as an experiment by developers, for developers, to remove the worst friction points of starting something new. The result is the most inclusive and prolific developer community in history, and a showcase for web projects you can’t find anywhere else.
                </p>
                <p className="py-3">
                Glitch provides a platform that brings their apps to life and simultaneously offers newcomers a broad foundation of examples to start their own adventures. From exploring virtual reality with WebXR, to creating inventive incremental games, to elevating the education of the next generation of web natives in bootcamps and schools, Glitch is home to thousands of communities already building their way through life.
                </p>
                <p className="py-3"></p>
                <p className="py-3"></p>
            </div>
            <div className="flex flex-row flex-wrap mx-auto ">
          <div className="relative transition-all duration-150 flex w-full px-6 py-4 md:w-1/2 lg:w-1/3">
            <div className="flex flex-col items-stretch min-h-full pb-4 mb-6 transition-all duration-150 ">
              <div className="flex">
                <Image
                  src={sumail}
                  className="object-fill w-10 h-10 rounded"
                  alt=""
                />
                <h1 className="flex items-end px-4 text-lg font-mabrybold leading-tight">
                    Anil Dash, CEO
                </h1>
              </div>

              <div className="flex flex-row flex-wrap w-full  py-2 overflow-hidden text-md font-mabry leading-snug text-justify text-gray-700">
              Anil fell in love with the web right at its start and he has been working to help people create their own pieces of the web ever since. He helped create some of the earliest social media publishing tools, was a former board member of Stack Overflow, and you can find him on Twitter talking about the music of Prince.
              </div>
            </div>
          </div>
          <div className="relative transition-all duration-150 flex w-full px-6 py-4 md:w-1/2 lg:w-1/3">
            <div className="flex flex-col items-stretch min-h-full pb-4 mb-6 transition-all duration-150 ">
              <div className="flex">
                <Image
                  src={mathew}
                  className="object-fill w-10 h-10 rounded"
                  alt=""
                />
                <h1 className="flex items-end px-4 text-lg font-mabrybold leading-tight">
                    Jenn Schiffer, Director of Community
                </h1>
              </div>

              <div className="flex flex-row flex-wrap w-full  py-2 overflow-hidden text-md font-mabry leading-snug text-justify text-gray-700">
              Jenn was first introduced to the web through being active in a number of creative communities, so it’s not too surprising that she found her way to Glitch. Here, she’s responsible for supporting, growing and advocating for the friendliest community of coders. She’s spoken at dozens of events around the world and online, and has won zero awards.
              </div>
            </div>
          </div>
          <div className="relative transition-all duration-150 flex w-full px-6 py-4 md:w-1/2 lg:w-1/3">
            <div className="flex flex-col items-stretch min-h-full pb-4 mb-6 transition-all duration-150 ">
              <div className="flex">
                <Image
                  src={mathew}
                  className="object-fill w-10 h-10 rounded"
                  alt=""
                />
                <h1 className="flex items-end text-lg px-4 font-mabrybold leading-tight">
                Jesse von Doom, Head of Product
                </h1>
              </div>

              <div className="flex flex-row flex-wrap w-full  py-2 overflow-hidden text-md font-mabry leading-snug text-justify text-gray-700">
              Art, design, and music brought Jesse to the web. Seeing the impact it has on peoples’ lives made him passionate about keeping the web open and accessible. He cofounded pioneering music tech nonprofit CASH Music, worked for other NGOs like the Mozilla Foundation, is a Shuttleworth Foundation fellow, and really enjoys rainbows.
              </div>
            </div>
          </div>
          <div className="relative transition-all duration-150 flex w-full px-6 py-4 md:w-1/2 lg:w-1/3">
            <div className="flex flex-col items-stretch min-h-full pb-4 mb-6 transition-all duration-150 ">
              <div className="flex">
                <Image
                  src={sumail}
                  className="object-fill w-10 h-10 rounded"
                  alt=""
                />
                <h1 className="flex items-end text-lg px-4 font-mabrybold leading-tight">
                Vatsal Patel, Head of Operations
                </h1>
              </div>

              <div className="flex flex-row flex-wrap w-full  py-2 overflow-hidden text-md font-mabry leading-snug text-justify text-gray-700">
              Vatsal brings deep industry and startup experience to Glitch, adding rigor and perspective to internal planning processes and decisions. His path here brought him through engineering and business roles that make him uniquely suited to facilitating success at a company that puts developers first.
              </div>
            </div>
          </div>
        </div>
          </div>
        </div>
        <Footer />
      </>
    );
}