import React from "react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";
import { CircularProgressbar, buildStyles } from "react-circular-progressbar";
import "react-circular-progressbar/dist/styles.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

import mine from "@/img/mine.jpg";
import fortnite from "@/img/fortnite.jpg";
import cyberpunk from "@/img/cyberpunk.jpg";
import lastofus from "@/img/lastofus.jpg";
import pga from "@/img/pga.jpg";
import callofduty from "@/img/callofduty.jpg";
import starwar from "@/img/starwar.jpeg";

export default function Reviews() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div className="h-max flex py-20 flex-col space-y-10 px-10 justify-center2 items-center2 bg-yellow-400">
        <div className="flex flex-row mx-auto  space-x-6 justify-center2 items-center">
          <span className="text-3xl font-mabrybold">Reviews</span>
        </div>
      </div>

      <div className="h-max flex pt-6 flex-col  px-10 justify-center2 items-center2 bg-[#f6f8f7]">
        <div className="flex flex-row mx-auto w-full space-x-6 justify-center2 items-center">
          <div className="flex justify-between w-full  px-4 py-4 rounded border-2 border-gray-800 bg-white">
            <div className="text-sm font-mabry">Showing 1-9 of 60825</div>
            <div className="flex space-x-2">
              <div className="text-sm font-mabry underline underline-offset-4 cursor-pointer">
                Clear
              </div>
              <div className="text-sm font-mabry underline underline-offset-4 cursor-pointer">
                Filter
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="h-max flex flex-col px-8 justify-center2 items-center2 bg-[#f6f8f7]">
        <div className="flex flex-row mx-auto w-full space-x-6 justify-center2 items-center">
          <section className="flex flex-row flex-wrap mx-auto justify-center2 items-center3">
            <div className=" transition-all duration-150 flex w-full px-2 py-4 md:w-1/3 lg:w-1/3 cursor-pointer">
              <div className=" flex flex-col border-2 border-gray-600 items-stretch min-h-full pb-4 mb-6 transition-all duration-150 bg-white rounded-lg shadow-lg hover:shadow-2xl">
                <div className="relative md:flex-shrink-0">
                  <Image
                    src={mine}
                    className="object-fill w-full rounded-lg rounded-b-none "
                    alt=""
                  />
                  <section className="absolute bottom-1 px-2 py-1 w-full">
                    <div className="flex  items-center justify-end">
                      <div className="h-8 w-8 md:h-10 md:w-10 rounded-full ">
                        <CircularProgressbar
                          value={69}
                          text={`${69}%`}
                          background
                          backgroundPadding={6}
                          styles={buildStyles({
                            textSize: "30px",
                            pathColor: "#fff",
                            textColor: "#fff",
                            trailColor: "transparent",
                            backgroundColor: "#3e98c7",
                          })}
                        />
                      </div>
                    </div>
                  </section>
                </div>

                <h1 className="px-4 pt-2 font-mabrybold font-bold ">
                  Lorem Ipsum dolor sit amet
                </h1>
              </div>
            </div>

            <div className="transition-all duration-150 flex w-full px-2 py-4 md:w-1/3 lg:w-1/3 cursor-pointer">
              <div className="flex flex-col border-2 border-gray-600 items-stretch min-h-full pb-4 mb-6 transition-all duration-150 bg-white rounded-lg shadow-lg hover:shadow-2xl">
                <div className="relative md:flex-shrink-0">
                  <Image
                    src={cyberpunk}
                    className="object-fill w-full rounded-lg rounded-b-none"
                    alt=""
                  />
                  <section className="absolute bottom-1 px-2 py-1 w-full">
                    <div className="flex  items-center justify-end">
                      <div className="h-8 w-8 md:h-10 md:w-10 rounded-full ">
                        <CircularProgressbar
                          value={69}
                          text={`${69}%`}
                          background
                          backgroundPadding={6}
                          styles={buildStyles({
                            textSize: "30px",
                            pathColor: "#fff",
                            textColor: "#fff",
                            trailColor: "transparent",
                            backgroundColor: "#3e98c7",
                          })}
                        />
                      </div>
                    </div>
                  </section>
                </div>

                <h1 className="px-4 pt-2 font-mabrybold font-bold">
                  Lorem Ipsum dolor sit amet
                </h1>
              </div>
            </div>

            <div className="transition-all duration-150 flex w-full px-2 py-4 md:w-1/3 lg:w-1/3 cursor-pointer">
              <div className="flex flex-col border-2 border-gray-600 items-stretch min-h-full pb-4 mb-6 transition-all duration-150 bg-white rounded-lg shadow-lg hover:shadow-2xl">
                <div className="relative  md:flex-shrink-0">
                  <Image
                    src={fortnite}
                    className="object-fill w-full rounded-lg rounded-b-none"
                    alt=""
                  />
                  <section className="absolute bottom-1 px-2 py-1 w-full">
                    <div className="flex  items-center justify-end">
                      <div className="h-8 w-8 md:h-10 md:w-10 rounded-full ">
                        <CircularProgressbar
                          value={69}
                          text={`${69}%`}
                          background
                          backgroundPadding={6}
                          styles={buildStyles({
                            textSize: "30px",
                            pathColor: "#fff",
                            textColor: "#fff",
                            trailColor: "transparent",
                            backgroundColor: "#3e98c7",
                          })}
                        />
                      </div>
                    </div>
                  </section>
                </div>

                <h1 className="px-4 pt-2 font-mabrybold font-bold">
                  Lorem Ipsum dolor sit amet
                </h1>
              </div>
            </div>

            <div className="transition-all duration-150 flex w-full px-2 py-4 md:w-1/3 lg:w-1/3 cursor-pointer">
              <div className="flex flex-col border-2 border-gray-600 items-stretch min-h-full pb-4 mb-6 transition-all duration-150 bg-white rounded-lg shadow-lg hover:shadow-2xl">
                <div className="relative  md:flex-shrink-0">
                  <Image
                    src={lastofus}
                    className="object-fill w-full rounded-lg rounded-b-none"
                    alt=""
                  />
                  <section className="absolute bottom-1 px-2 py-1 w-full">
                    <div className="flex  items-center justify-end">
                      <div className="h-8 w-8 md:h-10 md:w-10 rounded-full ">
                        <CircularProgressbar
                          value={69}
                          text={`${69}%`}
                          background
                          backgroundPadding={6}
                          styles={buildStyles({
                            textSize: "30px",
                            pathColor: "#fff",
                            textColor: "#fff",
                            trailColor: "transparent",
                            backgroundColor: "#3e98c7",
                          })}
                        />
                      </div>
                    </div>
                  </section>
                </div>

                <h1 className="px-4 pt-2 font-mabrybold font-bold">
                  Lorem Ipsum dolor sit amet
                </h1>
              </div>
            </div>

            <div className="transition-all duration-150 flex w-full px-2 py-4 md:w-1/3 lg:w-1/3 cursor-pointer">
              <div className="flex flex-col border-2 border-gray-600 items-stretch min-h-full pb-4 mb-6 transition-all duration-150 bg-white rounded-lg shadow-lg hover:shadow-2xl">
                <div className="relative  md:flex-shrink-0">
                  <Image
                    src={pga}
                    className="object-fill w-full rounded-lg rounded-b-none"
                    alt=""
                  />
                  <section className="absolute bottom-1 px-2 py-1 w-full">
                    <div className="flex  items-center justify-end">
                      <div className="h-8 w-8 md:h-10 md:w-10 rounded-full ">
                        <CircularProgressbar
                          value={69}
                          text={`${69}%`}
                          background
                          backgroundPadding={6}
                          styles={buildStyles({
                            textSize: "30px",
                            pathColor: "#fff",
                            textColor: "#fff",
                            trailColor: "transparent",
                            backgroundColor: "#3e98c7",
                          })}
                        />
                      </div>
                    </div>
                  </section>
                </div>

                <h1 className="px-4 pt-2 font-mabrybold font-bold">
                  Lorem Ipsum dolor sit amet
                </h1>
              </div>
            </div>

            <div className="transition-all duration-150 flex w-full px-2 py-4 md:w-1/3 lg:w-1/3 cursor-pointer">
              <div className="flex flex-col border-2 border-gray-600 items-stretch min-h-full pb-4 mb-6 transition-all duration-150 bg-white rounded-lg shadow-lg hover:shadow-2xl">
                <div className="relative  md:flex-shrink-0">
                  <Image
                    src={callofduty}
                    className="object-fill w-full rounded-lg rounded-b-none"
                    alt=""
                  />
                  <section className="absolute bottom-1 px-2 py-1 w-full">
                    <div className="flex  items-center justify-end">
                      <div className="h-8 w-8 md:h-10 md:w-10 rounded-full ">
                        <CircularProgressbar
                          value={69}
                          text={`${69}%`}
                          background
                          backgroundPadding={6}
                          styles={buildStyles({
                            textSize: "30px",
                            pathColor: "#fff",
                            textColor: "#fff",
                            trailColor: "transparent",
                            backgroundColor: "#3e98c7",
                          })}
                        />
                      </div>
                    </div>
                  </section>
                </div>

                <h1 className="px-4 pt-2 font-mabrybold font-bold">
                  Lorem Ipsum dolor sit amet
                </h1>
              </div>
            </div>

            <div className="transition-all duration-150 flex w-full px-2 py-4 md:w-1/3 lg:w-1/3 cursor-pointer">
              <div className="flex flex-col border-2 border-gray-600 items-stretch min-h-full pb-4 mb-6 transition-all duration-150 bg-white rounded-lg shadow-lg hover:shadow-2xl">
                <div className="relative  md:flex-shrink-0">
                  <Image
                    src={starwar}
                    className="object-fill w-full rounded-lg rounded-b-none"
                    alt=""
                  />
                  <section className="absolute bottom-1 px-2 py-1 w-full">
                    <div className="flex  items-center justify-end">
                      <div className="h-8 w-8 md:h-10 md:w-10 rounded-full ">
                        <CircularProgressbar
                          value={69}
                          text={`${69}%`}
                          background
                          backgroundPadding={6}
                          styles={buildStyles({
                            textSize: "30px",
                            pathColor: "#fff",
                            textColor: "#fff",
                            trailColor: "transparent",
                            backgroundColor: "#3e98c7",
                          })}
                        />
                      </div>
                    </div>
                  </section>
                </div>

                <h1 className="px-4 pt-2 font-mabrybold font-bold">
                  Lorem Ipsum dolor sit amet
                </h1>
              </div>
            </div>
          </section>
        </div>
      </div>

      <div className="h-max flex pb-6 flex-col space-y-10 px-10 justify-center2 items-center2 bg-[#f6f8f7]">
        <div className="flex flex-row mx-auto w-full space-x-6 justify-center2 items-center">
          <div className="flex justify-between items-center w-full  px-4 py-4 rounded border-2 border-gray-800 bg-white">
            <div>
              <nav
                aria-label="Pagination"
                className="flex items-center space-x-1 text-xs font-mabry text-gray-600"
              >
                <a href="#" className="p-1 rounded hover:bg-gray-100">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-4 w-4"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M15 19l-7-7 7-7"
                    />
                  </svg>
                </a>
                <a href="#" className="px-2 py-1 rounded hover:bg-gray-100">
                  {" "}
                  1{" "}
                </a>
                <a
                  href="#"
                  className="px-2 py-1 rounded bg-gray-200 text-gray-900 font-medium hover:bg-gray-100"
                >
                  {" "}
                  2{" "}
                </a>
                <a href="#" className="px-2 py-1 rounded hover:bg-gray-100">
                  {" "}
                  3{" "}
                </a>
                <a href="#" className="px-2 py-1 rounded hover:bg-gray-100">
                  {" "}
                  ...{" "}
                </a>
                <a href="#" className="px-2 py-1 rounded hover:bg-gray-100">
                  {" "}
                  9{" "}
                </a>
                <a href="#" className="p-1 rounded hover:bg-gray-100">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-4 w-4"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M9 5l7 7-7 7"
                    />
                  </svg>
                </a>
              </nav>
            </div>
            <div className="text-sm font-mabry">Showing 1-9 of 60825</div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}
