import React, { useEffect } from "react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

import tournament from "@/img/dota-tournament.jpg";
import dota from "@/img/dota-logo.png";

const Detail = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="bg-[#f4f2ef] relative py-6 md:py-12 ">
        <article className="max-w-3xl mx-auto relative z-10 py-4 md:py-8 px-1.5 md:px-4 markdown">
          <div className="container bg-white mx-auto mt-12 px-3 md:p-6 rounded-xl">
            <div className="px-4">
              <h1 className="py-5 font-mabryblack leading-tight text-3xl md:text-5xl tracking-tight font-display font-bold text-center">
                Bali Major 2023
              </h1>
            </div>{" "}
            <div className="mt-2 md:mt-2 flex justify-center  text-sm">
              <Image src={tournament} alt="" className="rounded-lg" />
            </div>
            <div className="w-full py-6 flex flex-col-reverse md:flex-row md:space-x-4">
              <div className="w-full md:w-3/5 bg-[#f4f2ef] rounded-lg p-4 mt-4 md:mt-0">
                <p className="font-mabry md:text-lg leading-tight">
                  While on PTO I more or less accidentally found a lot of
                  companies storing sensitive data in publicly accessible cloud
                  storage that can easily be scraped.
                </p>
              </div>
              <div className="w-full md:w-2/5 bg-[#4a5568] rounded-lg  text-white">
                <div className="flex flex-col w-full py-3 leading-tight">
                    <div className="flex justify-center items-center py-3">
                        <Image src={dota} alt="" />
                    </div>
                  <div className="flex justify-between items-center  py-2 px-3">
                    <div className="text-sm font-mabrybold">Disipline:</div>
                    <div className="text-sm font-mabry">Dota 2</div>
                  </div>
                  <div className="flex justify-between items-center  py-2 px-3">
                    <div className="text-sm font-mabrybold">Date:</div>
                    <div className="text-sm font-mabry">
                      29.06.23 - 09.07.23
                    </div>
                  </div>
                  <div className="flex justify-between items-center  py-2 px-3">
                    <div className="text-sm font-mabrybold">Prize:</div>
                    <div className="text-sm font-mabry">$500 000</div>
                  </div>
                  <div className="flex justify-between items-center  border-gray-800 py-2 px-3">
                    <div className="text-sm font-mabrybold">Type:</div>
                    <div className="text-sm font-mabry">Offline</div>
                  </div>
                  <div className="flex justify-between items-center  border-gray-800 py-2 px-3">
                    <div className="text-sm font-mabrybold">Organizers:</div>
                    <div className="text-sm font-mabry">Epulze IO Sport</div>
                  </div>
                  <div className="flex justify-between items-center  border-gray-800 py-2 px-3">
                    <div className="text-sm font-mabrybold">Venue:</div>
                    <div className="text-sm font-mabry">Ayana</div>
                  </div>
                  <div className="flex justify-between items-center  border-gray-800 py-2 px-3">
                    <div className="text-sm font-mabrybold">Sponsor:</div>
                    <div className="text-sm font-mabry">Ayana</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </article>
      </div>
      <Footer />
    </>
  );
};

export default Detail;
