import React, { useEffect } from "react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

const terms = () => {

    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <div class="bg-splatter-x relative py-12">
          <article class="max-w-3xl mx-auto relative z-10 py-8 px-4 markdown">
            <div class="bg-rain h-full w-8 hidden md:block absolute top-0 left-0 -ml-16 mt-8"></div>{" "}
            <h1 class="text-3xl font-mabryblack">Terms &amp; Conditions</h1>{" "}
            <p class="py-4 leading-tight text-pink-400 font-mabryitalic text-2xl">
              This stuff is boring, but important. In short, be a decent human
              being.
            </p>{" "}
            <p className="py-2 font-mabry">
              By using the this website (“Service”), or any services of
              STATAMIC, you are agreeing to be bound by the following terms and
              conditions (“Terms of Service”). IF YOU ARE ENTERING INTO THIS
              AGREEMENT ON BEHALF OF A COMPANY OR OTHER LEGAL ENTITY, YOU
              REPRESENT THAT YOU HAVE THE AUTHORITY TO BIND SUCH ENTITY, ITS
              AFFILIATES AND ALL USERS WHO ACCESS OUR SERVICES THROUGH YOUR
              ACCOUNT TO THESE TERMS AND CONDITIONS, IN WHICH CASE THE TERMS
              “YOU” OR “YOUR” SHALL REFER TO SUCH ENTITY, ITS AFFILIATES AND
              USERS ASSOCIATED WITH IT. IF YOU DO NOT HAVE SUCH AUTHORITY, OR IF
              YOU DO NOT AGREE WITH THESE TERMS AND CONDITIONS, YOU MUST NOT
              ACCEPT THIS AGREEMENT AND MAY NOT USE THE&nbsp;SERVICES.
            </p>{" "}
            <p className="py-2 font-mabry">
              If we make material changes to these Terms, we will notify you by
              email or by posting a notice on our site before the changes are
              effective. Any new features that augment or enhance the current
              Service, including the release of new tools and resources, shall
              be subject to the Terms of Service. Continued use of the Service
              after any such changes shall constitute your consent to
              such&nbsp;changes.
            </p>{" "}
            <p className="py-2 font-mabry">
              Violation of any of the terms below will result in the termination
              of your Account. While we prohibit such conduct and Content on the
              Service, you understand and agree that we cannot be responsible
              for the Content posted on the Service and you nonetheless may be
              exposed to such materials. You agree to use the Service at your
              own&nbsp;risk.
            </p>{" "}
            <h3 className="py-3 font-mabryblack text-lg">Account&nbsp;Terms</h3>{" "}
            <ul className="list-disc space-y-2 font-mabry">
              <li>
                You must be 13 years or older or have permission from a parent
                or legal guardian to use this&nbsp;Service.
              </li>{" "}
              <li>
                You must be a human. Accounts registered by “bots” or other
                automated methods are not&nbsp;permitted.
              </li>{" "}
              <li>
                You must provide your name, a valid email address, and any other
                information requested in order to complete the
                signup&nbsp;process.
              </li>{" "}
              <li>
                You are responsible for maintaining the security of your account
                and password. We cannot and will not be liable for any loss or
                damage from your failure to comply with this
                security&nbsp;obligation.
              </li>{" "}
              <li>
                You are responsible for all Content posted and activity that
                occurs under your account (even when Content is posted by others
                who have accounts under your&nbsp;account).
              </li>{" "}
              <li>
                You may not use the Service for any illegal or unauthorized
                purpose. You must not, in the use of the Service, violate any
                laws in your jurisdiction (including but not limited to
                copyright or trademark&nbsp;laws).
              </li>
            </ul>{" "}
            <h3 className="py-3 font-mabryblack text-lg">Copyright and Content&nbsp;Ownership</h3>{" "}
            <ul className="list-disc space-y-2 font-mabry">
              <li>
                We claim no intellectual property rights over the material you
                provide to the Service. Your profile and materials uploaded
                remain&nbsp;yours.
              </li>{" "}
              <li>
                We don’t pre-screen Content, but we have the right (but not the
                obligation) in our sole discretion to refuse or remove any
                Content that is available via the&nbsp;Service.
              </li>{" "}
              <li>
                The look and feel of the Service is copyrighted by Statamic. All
                rights reserved. You may not duplicate, copy, or reuse any
                portion of the HTML/CSS, Javascript, or visual design elements
                or concepts without express written permission
                from&nbsp;Statamic.
              </li>
            </ul>{" "}
            <h3 className="py-3 font-mabryblack text-lg">General&nbsp;Conditions</h3>{" "}
            <ul className="list-disc space-y-2 font-mabry">
              <li>
                Your use of the Service is at your sole risk. The service is
                provided on an “as is” and “as available”&nbsp;basis.
              </li>{" "}
              <li>
                Support for Statamic services is only available in English,
                via&nbsp;email.
              </li>{" "}
              <li>
                You understand that we use third-party vendors and hosting
                partners to provide the necessary hardware, software,
                networking, storage, and related technology required to run
                the&nbsp;Service.
              </li>{" "}
              <li>
                You must not modify, adapt or hack the Service or modify another
                website so as to falsely imply that it is associated with the
                Service, Statamic, or any other Statamic&nbsp;service.
              </li>{" "}
              <li>
                You agree not to reproduce, duplicate, copy, sell, resell or
                exploit any portion of the Service, use of the Service, or
                access to the Service without the express written permission
                by&nbsp;Statamic.
              </li>{" "}
              <li>
                We may, but have no obligation to, remove Content and Accounts
                containing Content that we determine in our sole discretion are
                unlawful, offensive, threatening, libelous, defamatory,
                pornographic, obscene or otherwise objectionable or violates any
                party’s intellectual property or these Terms of&nbsp;Service.
              </li>{" "}
              <li>
                Verbal, physical, written or other abuse (including threats of
                abuse or retribution) of any Statamic customer, employee,
                member, or officer will result in immediate
                account&nbsp;termination.
              </li>{" "}
              <li>
                You must not upload, post, host, or transmit unsolicited email,
                SMSs, or “spam”&nbsp;messages.
              </li>{" "}
              <li>
                You must not transmit any worms or viruses or any code of a
                destructive&nbsp;nature.
              </li>{" "}
              <li>
                You expressly understand and agree that Statamic shall not be
                liable for any direct, indirect, incidental, special,
                consequential or exemplary damages, including but not limited
                to, damages for loss of profits, goodwill, use, data or other
                intangible losses (even if Statamic has been advised of the
                possibility of such damages), resulting from: (i) the use or the
                inability to use the service; (ii) the cost of procurement of
                substitute goods and services resulting from any goods, data,
                information or services purchased or obtained or messages
                received or transactions entered into through or from the
                service; (iii) unauthorized access to or alteration of your
                transmissions or data; (iv) statements or conduct of any
                third-party on the service; (v) or any other matter relating to
                the&nbsp;service.
              </li>
            </ul>{" "}
            <p className="font-mabry py-3">
              Any questions about these Terms of Service should be addressed
              to&nbsp;<a href="mailto:hello@statamic.com">hello@statamic.com</a>
              .
            </p>{" "}
            <p className="font-mabry">
              <em>Last updated: November 30th,&nbsp;2020.</em>
            </p>
          </article>
        </div>
        <Footer />
      </>
    );
};

export default terms;