import React, { useEffect } from "react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

import lastofus from "@/img/lastofus.jpg";
import leon from "@/img/leon.png";
import cod from "@/img/cod.jpg";

export default function Guides() {
  //   useEffect(() => {
  //     window.scrollTo(0, 0);
  //   }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div className=" flex justify-center text-sm mt-16">
        <Image src={leon} alt="" className="rounded-3xl my-6" />
      </div>
      <div className="h-max flex flex-col mt-2">
        <div className="flex flex-row mx-auto w-full justify-center2 items-center">
          <div className="flex justify-between w-full  px-8 py-4 border-y border-gray-800 bg-white">
            <div className="flex  items-center space-x-2">
              <select
                id="countries"
                class="bg-yellow-100 border border-gray-800 text-gray-900 text-sm font-mabry rounded focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              >
                <option selected>Sort</option>
                <option value="US">United States</option>
                <option value="CA">Canada</option>
                <option value="FR">France</option>
                <option value="DE">Germany</option>
              </select>
              <select
                id="countries"
                class="bg-yellow-100 border border-gray-800 text-gray-900 text-sm font-mabry rounded focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              >
                <option selected>Score</option>
                <option value="US">United States</option>
                <option value="CA">Canada</option>
                <option value="FR">France</option>
                <option value="DE">Germany</option>
              </select>
              <select
                id="countries"
                class="bg-yellow-100 border border-gray-800 text-gray-900 font-mabry text-sm rounded focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              >
                <option selected>Platform</option>
                <option value="US">United States</option>
                <option value="CA">Canada</option>
                <option value="FR">France</option>
                <option value="DE">Germany</option>
              </select>
              <select
                id="countries"
                class="bg-yellow-100 border border-gray-800 text-gray-900 text-sm font-mabry rounded focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              >
                <option selected>Genre</option>
                <option value="US">United States</option>
                <option value="CA">Canada</option>
                <option value="FR">France</option>
                <option value="DE">Germany</option>
              </select>
            </div>
          </div>
        </div>
      </div>

      <section className="bg-[#f6f8f7]">
        <div className="container w-full md:max-w-4xl mx-auto pt-4 md:pt-10 pb-10">
          <div className="w-full px-4 md:px-6 text-lg text-gray-800 leading-normal">
            <div className="flex w-full space-x-3">
              <div className="flex flex-col space-y-5 w-2/3 text-md font-mabry leading-tight pr-4 border-r">
                <Link href={""}>
                  <div className="relative flex flex-row w-full mx-auto space-x-4 justify-center2 items-center bg-white px-4 py-4 rounded-md shadow">
                    <div className="w-1/3">
                      <Image src={cod} alt="" />
                    </div>
                    <div className="flex w-2/3 flex-col space-y-1">
                      <div className="text-[16px] font-mabrybold">
                        Build that thing you’ve been imagining
                      </div>
                      <span className="text-[13px] leading-snug">
                        Millions of people use Glitch to express themselves, try
                        new things, and help others learn. We’re fun and easy,
                      </span>
                      <div className="flex space-x-3 items-center text-red-600">
                        <div className="text-[10px] font-mabry py-1 px-2 border-red-700 rounded-lg bg-red-300 text-red-700 capitalize">
                          call of duty
                        </div>
                        <div className="flex space-x-1 items-center">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            fill="currentColor"
                            className="w-4 h-4"
                          >
                            <path
                              fillRule="evenodd"
                              d="M18.685 19.097A9.723 9.723 0 0021.75 12c0-5.385-4.365-9.75-9.75-9.75S2.25 6.615 2.25 12a9.723 9.723 0 003.065 7.097A9.716 9.716 0 0012 21.75a9.716 9.716 0 006.685-2.653zm-12.54-1.285A7.486 7.486 0 0112 15a7.486 7.486 0 015.855 2.812A8.224 8.224 0 0112 20.25a8.224 8.224 0 01-5.855-2.438zM15.75 9a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0z"
                              clipRule="evenodd"
                            />
                          </svg>
                          <span className="text-[11px] font-mabry">Anna</span>
                        </div>
                        <div className="flex space-x-1 items-center text-red-600">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            fill="currentColor"
                            className="w-4 h-4"
                          >
                            <path
                              fillRule="evenodd"
                              d="M4.804 21.644A6.707 6.707 0 006 21.75a6.721 6.721 0 003.583-1.029c.774.182 1.584.279 2.417.279 5.322 0 9.75-3.97 9.75-9 0-5.03-4.428-9-9.75-9s-9.75 3.97-9.75 9c0 2.409 1.025 4.587 2.674 6.192.232.226.277.428.254.543a3.73 3.73 0 01-.814 1.686.75.75 0 00.44 1.223zM8.25 10.875a1.125 1.125 0 100 2.25 1.125 1.125 0 000-2.25zM10.875 12a1.125 1.125 0 112.25 0 1.125 1.125 0 01-2.25 0zm4.875-1.125a1.125 1.125 0 100 2.25 1.125 1.125 0 000-2.25z"
                              clipRule="evenodd"
                            />
                          </svg>

                          <span className="text-[11px] font-mabry">100</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </Link>
                <Link href={""}>
                  <div className="relative flex flex-row w-full mx-auto space-x-4 justify-center2 items-center bg-white px-4 py-4 rounded-md shadow">
                    <div className="w-1/3">
                      <Image src={cod} alt="" />
                    </div>
                    <div className="flex w-2/3 flex-col space-y-1">
                      <div className="text-[16px] font-mabrybold">
                        Build that thing you’ve been imagining
                      </div>
                      <span className="text-[13px] leading-snug">
                        Millions of people use Glitch to express themselves, try
                        new things, and help others learn. We’re fun and easy,
                      </span>
                      <div className="flex space-x-3 items-center text-red-600">
                        <div className="text-[10px] font-mabry py-1 px-2 border-red-700 rounded-lg bg-red-300 text-red-700 capitalize">
                          call of duty
                        </div>
                        <div className="flex space-x-1 items-center">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            fill="currentColor"
                            className="w-4 h-4"
                          >
                            <path
                              fillRule="evenodd"
                              d="M18.685 19.097A9.723 9.723 0 0021.75 12c0-5.385-4.365-9.75-9.75-9.75S2.25 6.615 2.25 12a9.723 9.723 0 003.065 7.097A9.716 9.716 0 0012 21.75a9.716 9.716 0 006.685-2.653zm-12.54-1.285A7.486 7.486 0 0112 15a7.486 7.486 0 015.855 2.812A8.224 8.224 0 0112 20.25a8.224 8.224 0 01-5.855-2.438zM15.75 9a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0z"
                              clipRule="evenodd"
                            />
                          </svg>
                          <span className="text-[11px] font-mabry">Anna</span>
                        </div>
                        <div className="flex space-x-1 items-center text-red-600">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            fill="currentColor"
                            className="w-4 h-4"
                          >
                            <path
                              fillRule="evenodd"
                              d="M4.804 21.644A6.707 6.707 0 006 21.75a6.721 6.721 0 003.583-1.029c.774.182 1.584.279 2.417.279 5.322 0 9.75-3.97 9.75-9 0-5.03-4.428-9-9.75-9s-9.75 3.97-9.75 9c0 2.409 1.025 4.587 2.674 6.192.232.226.277.428.254.543a3.73 3.73 0 01-.814 1.686.75.75 0 00.44 1.223zM8.25 10.875a1.125 1.125 0 100 2.25 1.125 1.125 0 000-2.25zM10.875 12a1.125 1.125 0 112.25 0 1.125 1.125 0 01-2.25 0zm4.875-1.125a1.125 1.125 0 100 2.25 1.125 1.125 0 000-2.25z"
                              clipRule="evenodd"
                            />
                          </svg>

                          <span className="text-[11px] font-mabry">100</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </Link>
                <Link href={""}>
                  <div className="relative flex flex-row w-full mx-auto space-x-4 justify-center2 items-center bg-white px-4 py-4 rounded-md shadow">
                    <div className="w-1/3">
                      <Image src={cod} alt="" />
                    </div>
                    <div className="flex w-2/3 flex-col space-y-1">
                      <div className="text-[16px] font-mabrybold">
                        Build that thing you’ve been imagining
                      </div>
                      <span className="text-[13px] leading-snug">
                        Millions of people use Glitch to express themselves, try
                        new things, and help others learn. We’re fun and easy,
                      </span>
                      <div className="flex space-x-3 items-center text-red-600">
                        <div className="text-[10px] font-mabry py-1 px-2 border-red-700 rounded-lg bg-red-300 text-red-700 capitalize">
                          call of duty
                        </div>
                        <div className="flex space-x-1 items-center">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            fill="currentColor"
                            className="w-4 h-4"
                          >
                            <path
                              fillRule="evenodd"
                              d="M18.685 19.097A9.723 9.723 0 0021.75 12c0-5.385-4.365-9.75-9.75-9.75S2.25 6.615 2.25 12a9.723 9.723 0 003.065 7.097A9.716 9.716 0 0012 21.75a9.716 9.716 0 006.685-2.653zm-12.54-1.285A7.486 7.486 0 0112 15a7.486 7.486 0 015.855 2.812A8.224 8.224 0 0112 20.25a8.224 8.224 0 01-5.855-2.438zM15.75 9a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0z"
                              clipRule="evenodd"
                            />
                          </svg>
                          <span className="text-[11px] font-mabry">Anna</span>
                        </div>
                        <div className="flex space-x-1 items-center text-red-600">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            fill="currentColor"
                            className="w-4 h-4"
                          >
                            <path
                              fillRule="evenodd"
                              d="M4.804 21.644A6.707 6.707 0 006 21.75a6.721 6.721 0 003.583-1.029c.774.182 1.584.279 2.417.279 5.322 0 9.75-3.97 9.75-9 0-5.03-4.428-9-9.75-9s-9.75 3.97-9.75 9c0 2.409 1.025 4.587 2.674 6.192.232.226.277.428.254.543a3.73 3.73 0 01-.814 1.686.75.75 0 00.44 1.223zM8.25 10.875a1.125 1.125 0 100 2.25 1.125 1.125 0 000-2.25zM10.875 12a1.125 1.125 0 112.25 0 1.125 1.125 0 01-2.25 0zm4.875-1.125a1.125 1.125 0 100 2.25 1.125 1.125 0 000-2.25z"
                              clipRule="evenodd"
                            />
                          </svg>

                          <span className="text-[11px] font-mabry">100</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </Link>
                <Link href={""}>
                  <div className="relative flex flex-row w-full mx-auto space-x-4 justify-center2 items-center bg-white px-4 py-4 rounded-md shadow">
                    <div className="w-1/3">
                      <Image src={cod} alt="" />
                    </div>
                    <div className="flex w-2/3 flex-col space-y-1">
                      <div className="text-[16px] font-mabrybold">
                        Build that thing you’ve been imagining
                      </div>
                      <span className="text-[13px] leading-snug">
                        Millions of people use Glitch to express themselves, try
                        new things, and help others learn. We’re fun and easy,
                      </span>
                      <div className="flex space-x-3 items-center text-red-600">
                        <div className="text-[10px] font-mabry py-1 px-2 border-red-700 rounded-lg bg-red-300 text-red-700 capitalize">
                          call of duty
                        </div>
                        <div className="flex space-x-1 items-center">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            fill="currentColor"
                            className="w-4 h-4"
                          >
                            <path
                              fillRule="evenodd"
                              d="M18.685 19.097A9.723 9.723 0 0021.75 12c0-5.385-4.365-9.75-9.75-9.75S2.25 6.615 2.25 12a9.723 9.723 0 003.065 7.097A9.716 9.716 0 0012 21.75a9.716 9.716 0 006.685-2.653zm-12.54-1.285A7.486 7.486 0 0112 15a7.486 7.486 0 015.855 2.812A8.224 8.224 0 0112 20.25a8.224 8.224 0 01-5.855-2.438zM15.75 9a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0z"
                              clipRule="evenodd"
                            />
                          </svg>
                          <span className="text-[11px] font-mabry">Anna</span>
                        </div>
                        <div className="flex space-x-1 items-center text-red-600">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            fill="currentColor"
                            className="w-4 h-4"
                          >
                            <path
                              fillRule="evenodd"
                              d="M4.804 21.644A6.707 6.707 0 006 21.75a6.721 6.721 0 003.583-1.029c.774.182 1.584.279 2.417.279 5.322 0 9.75-3.97 9.75-9 0-5.03-4.428-9-9.75-9s-9.75 3.97-9.75 9c0 2.409 1.025 4.587 2.674 6.192.232.226.277.428.254.543a3.73 3.73 0 01-.814 1.686.75.75 0 00.44 1.223zM8.25 10.875a1.125 1.125 0 100 2.25 1.125 1.125 0 000-2.25zM10.875 12a1.125 1.125 0 112.25 0 1.125 1.125 0 01-2.25 0zm4.875-1.125a1.125 1.125 0 100 2.25 1.125 1.125 0 000-2.25z"
                              clipRule="evenodd"
                            />
                          </svg>

                          <span className="text-[11px] font-mabry">100</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </Link>
                <Link href={""}>
                  <div className="relative flex flex-row w-full mx-auto space-x-4 justify-center2 items-center bg-white px-4 py-4 rounded-md shadow">
                    <div className="w-1/3">
                      <Image src={cod} alt="" />
                    </div>
                    <div className="flex w-2/3 flex-col space-y-1">
                      <div className="text-[16px] font-mabrybold">
                        Build that thing you’ve been imagining
                      </div>
                      <span className="text-[13px] leading-snug">
                        Millions of people use Glitch to express themselves, try
                        new things, and help others learn. We’re fun and easy,
                      </span>
                      <div className="flex space-x-3 items-center text-red-600">
                        <div className="text-[10px] font-mabry py-1 px-2 border-red-700 rounded-lg bg-red-300 text-red-700 capitalize">
                          call of duty
                        </div>
                        <div className="flex space-x-1 items-center">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            fill="currentColor"
                            className="w-4 h-4"
                          >
                            <path
                              fillRule="evenodd"
                              d="M18.685 19.097A9.723 9.723 0 0021.75 12c0-5.385-4.365-9.75-9.75-9.75S2.25 6.615 2.25 12a9.723 9.723 0 003.065 7.097A9.716 9.716 0 0012 21.75a9.716 9.716 0 006.685-2.653zm-12.54-1.285A7.486 7.486 0 0112 15a7.486 7.486 0 015.855 2.812A8.224 8.224 0 0112 20.25a8.224 8.224 0 01-5.855-2.438zM15.75 9a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0z"
                              clipRule="evenodd"
                            />
                          </svg>
                          <span className="text-[11px] font-mabry">Anna</span>
                        </div>
                        <div className="flex space-x-1 items-center text-red-600">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            fill="currentColor"
                            className="w-4 h-4"
                          >
                            <path
                              fillRule="evenodd"
                              d="M4.804 21.644A6.707 6.707 0 006 21.75a6.721 6.721 0 003.583-1.029c.774.182 1.584.279 2.417.279 5.322 0 9.75-3.97 9.75-9 0-5.03-4.428-9-9.75-9s-9.75 3.97-9.75 9c0 2.409 1.025 4.587 2.674 6.192.232.226.277.428.254.543a3.73 3.73 0 01-.814 1.686.75.75 0 00.44 1.223zM8.25 10.875a1.125 1.125 0 100 2.25 1.125 1.125 0 000-2.25zM10.875 12a1.125 1.125 0 112.25 0 1.125 1.125 0 01-2.25 0zm4.875-1.125a1.125 1.125 0 100 2.25 1.125 1.125 0 000-2.25z"
                              clipRule="evenodd"
                            />
                          </svg>

                          <span className="text-[11px] font-mabry">100</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </Link>
                <Link href={""}>
                  <div className="relative flex flex-row w-full mx-auto space-x-4 justify-center2 items-center bg-white px-4 py-4 rounded-md shadow">
                    <div className="w-1/3">
                      <Image src={cod} alt="" />
                    </div>
                    <div className="flex w-2/3 flex-col space-y-1">
                      <div className="text-[16px] font-mabrybold">
                        Build that thing you’ve been imagining
                      </div>
                      <span className="text-[13px] leading-snug">
                        Millions of people use Glitch to express themselves, try
                        new things, and help others learn. We’re fun and easy,
                      </span>
                      <div className="flex space-x-3 items-center text-red-600">
                        <div className="text-[10px] font-mabry py-1 px-2 border-red-700 rounded-lg bg-red-300 text-red-700 capitalize">
                          call of duty
                        </div>
                        <div className="flex space-x-1 items-center">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            fill="currentColor"
                            className="w-4 h-4"
                          >
                            <path
                              fillRule="evenodd"
                              d="M18.685 19.097A9.723 9.723 0 0021.75 12c0-5.385-4.365-9.75-9.75-9.75S2.25 6.615 2.25 12a9.723 9.723 0 003.065 7.097A9.716 9.716 0 0012 21.75a9.716 9.716 0 006.685-2.653zm-12.54-1.285A7.486 7.486 0 0112 15a7.486 7.486 0 015.855 2.812A8.224 8.224 0 0112 20.25a8.224 8.224 0 01-5.855-2.438zM15.75 9a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0z"
                              clipRule="evenodd"
                            />
                          </svg>
                          <span className="text-[11px] font-mabry">Anna</span>
                        </div>
                        <div className="flex space-x-1 items-center text-red-600">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            fill="currentColor"
                            className="w-4 h-4"
                          >
                            <path
                              fillRule="evenodd"
                              d="M4.804 21.644A6.707 6.707 0 006 21.75a6.721 6.721 0 003.583-1.029c.774.182 1.584.279 2.417.279 5.322 0 9.75-3.97 9.75-9 0-5.03-4.428-9-9.75-9s-9.75 3.97-9.75 9c0 2.409 1.025 4.587 2.674 6.192.232.226.277.428.254.543a3.73 3.73 0 01-.814 1.686.75.75 0 00.44 1.223zM8.25 10.875a1.125 1.125 0 100 2.25 1.125 1.125 0 000-2.25zM10.875 12a1.125 1.125 0 112.25 0 1.125 1.125 0 01-2.25 0zm4.875-1.125a1.125 1.125 0 100 2.25 1.125 1.125 0 000-2.25z"
                              clipRule="evenodd"
                            />
                          </svg>

                          <span className="text-[11px] font-mabry">100</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </Link>
                <Link href={""}>
                  <div className="relative flex flex-row w-full mx-auto space-x-4 justify-center2 items-center bg-white px-4 py-4 rounded-md shadow">
                    <div className="w-1/3">
                      <Image src={cod} alt="" />
                    </div>
                    <div className="flex w-2/3 flex-col space-y-1">
                      <div className="text-[16px] font-mabrybold">
                        Build that thing you’ve been imagining
                      </div>
                      <span className="text-[13px] leading-snug">
                        Millions of people use Glitch to express themselves, try
                        new things, and help others learn. We’re fun and easy,
                      </span>
                      <div className="flex space-x-3 items-center text-red-600">
                        <div className="text-[10px] font-mabry py-1 px-2 border-red-700 rounded-lg bg-red-300 text-red-700 capitalize">
                          call of duty
                        </div>
                        <div className="flex space-x-1 items-center">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            fill="currentColor"
                            className="w-4 h-4"
                          >
                            <path
                              fillRule="evenodd"
                              d="M18.685 19.097A9.723 9.723 0 0021.75 12c0-5.385-4.365-9.75-9.75-9.75S2.25 6.615 2.25 12a9.723 9.723 0 003.065 7.097A9.716 9.716 0 0012 21.75a9.716 9.716 0 006.685-2.653zm-12.54-1.285A7.486 7.486 0 0112 15a7.486 7.486 0 015.855 2.812A8.224 8.224 0 0112 20.25a8.224 8.224 0 01-5.855-2.438zM15.75 9a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0z"
                              clipRule="evenodd"
                            />
                          </svg>
                          <span className="text-[11px] font-mabry">Anna</span>
                        </div>
                        <div className="flex space-x-1 items-center text-red-600">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            fill="currentColor"
                            className="w-4 h-4"
                          >
                            <path
                              fillRule="evenodd"
                              d="M4.804 21.644A6.707 6.707 0 006 21.75a6.721 6.721 0 003.583-1.029c.774.182 1.584.279 2.417.279 5.322 0 9.75-3.97 9.75-9 0-5.03-4.428-9-9.75-9s-9.75 3.97-9.75 9c0 2.409 1.025 4.587 2.674 6.192.232.226.277.428.254.543a3.73 3.73 0 01-.814 1.686.75.75 0 00.44 1.223zM8.25 10.875a1.125 1.125 0 100 2.25 1.125 1.125 0 000-2.25zM10.875 12a1.125 1.125 0 112.25 0 1.125 1.125 0 01-2.25 0zm4.875-1.125a1.125 1.125 0 100 2.25 1.125 1.125 0 000-2.25z"
                              clipRule="evenodd"
                            />
                          </svg>

                          <span className="text-[11px] font-mabry">100</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </Link>
              </div>
              <div className="w-1/3 ">
                <div className="flex flex-col space-y-2 px-2 w-full">
                  <div>
                    <span className="text-sm capitalize font-mabrybold">
                      suggested topic
                    </span>
                  </div>
                  <div className="flex flex-wrap space-x-1 w-60">
                    <a
                      href="#"
                      className="m-1 flex flex-wrap items-center text-xs font-mabry md:text-xs text-indigo-500 border border-indigo-500 py-1 px-2 rounded-full bg-indigo-200 capitalize "
                    >
                      action
                    </a>{" "}
                    <a
                      href="#"
                      className="m-1 flex flex-wrap items-center text-xs font-mabry md:text-xs text-green-500 border border-green-500 py-1 px-2 rounded-full bg-green-200 capitalize "
                    >
                      adventure
                    </a>{" "}
                    <a
                      href="#"
                      className="m-1 flex flex-wrap items-center text-xs font-mabry md:text-xs text-orange-500 border border-orange-500 py-1 px-2 rounded-full bg-orange-200 capitalize "
                    >
                      adventure
                    </a>{" "}
                    <a
                      href="#"
                      className="m-1 flex flex-wrap items-center text-xs font-mabry md:text-xs text-blue-500 border border-blue-500 py-1 px-2 rounded-full bg-blue-200 capitalize "
                    >
                      rpg
                    </a>{" "}
                    <a
                      href="#"
                      className="m-1 flex flex-wrap items-center text-xs font-mabry md:text-xs text-yellow-500 border border-yellow-500 py-1 px-2 rounded-full bg-yellow-200 capitalize "
                    >
                      sport
                    </a>{" "}
                    <a
                      href="#"
                      className="m-1 flex flex-wrap items-center text-xs font-mabry md:text-xs text-red-500 border border-red-500 py-1 px-2 rounded-full bg-red-200 capitalize "
                    >
                      racing
                    </a>{" "}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <Footer />
    </>
  );
}
