import React from "react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import Notice from "@/components/Notice";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import GoTop from "@/components/GoTop";

import person from "@/img/300.jpg";

export default function Profile() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* <Notice /> */}
      <GoTop />

      <section className="bg-white">
        <div className="w-full bg-center bg-gray-800 h-60"></div>

        <div className="container mx-auto">
          <div className="flex justify-center lg:justify-start">
            <Image
              src={person}
              className="bg-gray-50 rounded-full -mt-24 w-48 h-48 border-8 border-white"
            />
          </div>

          <div className="flex flex-col mt-5 p-4 lg:flex-row lg:gap-x-12">
            <div className="w-full mb-10 lg:w-1/3 lg:mb-0">
              <div>
                <div className="flex items-center gap-x-4">
                  <h1 className="text-4xl font-mabrybold">MacWorks</h1>
                </div>

                <span className="text-gray-600 font-mabry">Joined 6 Feb 2014</span>
              </div>

              <div className="mt-4">
                <span className="text-gray-900"></span>
              </div>

              <div className="mt-4 mb-6 flex items-center gap-x-3">
                <a href="https://github.com/MacWorks">
                  <svg
                    className="w-6 h-6"
                    viewBox="0 0 24 24"
                    fill="currentColor"
                  >
                    <path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"></path>
                  </svg>{" "}
                </a>
              </div>

              <div className="flex flex-col gap-y-4">
                <span className="inline-flex rounded-md shadow">
                  <button className="bg-white border border-red-400 rounded py-2 px-4 inline-flex justify-center text-base font-mabry text-red-500 hover:bg-red-50 font-medium w-full">
                    <span className="flex items-center gap-x-2">
                      <svg
                        className="w-5 h-5"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke-width="1.5"
                        stroke="currentColor"
                        aria-hidden="true"
                      >
                        <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          d="M6 18L18 6M6 6l12 12"
                        ></path>
                      </svg>{" "}
                      Block User
                    </span>
                  </button>
                </span>
              </div>
            </div>

            <div className="w-full lg:w-2/3">
              <h2 className="text-3xl font-semibold font-mabrybold">Statistics</h2>

              <div className="mt-4 grid grid-cols-1 lg:grid-cols-2 font-mabry">
                <div className="w-full flex justify-between px-5 py-2.5 bg-gray-100">
                  <span>Threads</span>
                  <span className="text-lio-500">6</span>
                </div>

                <div className="w-full flex justify-between px-5 py-2.5 bg-white lg:bg-gray-100">
                  <span>Replies</span>
                  <span className="text-lio-500">13</span>
                </div>

                <div className="w-full flex justify-between px-5 py-2.5 bg-gray-100 lg:bg-white">
                  <span>Solutions</span>
                  <span className="text-lio-500">2</span>
                </div>

                <div className="w-full flex justify-between px-5 py-2.5">
                  <span>Articles</span>
                  <span className="text-lio-500">0</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="mt-16 lg:mt-32">
          <div className="container mx-auto font-mabry">
            <nav className="flex items-center justify-between lg:justify-start">
              <button className="px-4 whitespace-nowrap py-5 font-medium text-lg text-gray-900 hover:text-lio-500 hover:border-lio-500 focus:outline-none focus:text-lio-500 focus:border-lio-500 lg:w-1/3 text-lio-500 border-lio-500 border-b-2">
                Threads posted
              </button>
              <button className="px-4 whitespace-nowrap py-5 font-medium text-lg text-gray-900 hover:text-lio-500 hover:border-lio-500 focus:outline-none focus:text-lio-500 focus:border-lio-500 lg:w-1/3">
                Replies posted
              </button>
            </nav>
          </div>

          <div className="bg-gray-100 py-14 px-4">
            <div className="container mx-auto">
              <div x-show="tab === &#39;threads&#39;">
                <div className="flex flex-col gap-y-6">
                  <div className="h-full rounded shadow-lg p-5 bg-white">
                    <div className="flex flex-col lg:flex-row lg:justify-between lg:items-center">
                      <div>
                        <div className="flex flex-wrap items-center space-x-1 text-sm">
                          <div className="flex items-center">
                            <a href="https://laravel.io/user/macworks">
                              <Image
                                src={person}
                                className="bg-gray-50 rounded-full w-6 h-6 mr-2"
                              />
                            </a>

                            <a
                              href="https://laravel.io/user/macworks"
                              className="hover:underline"
                            >
                              <span className="text-gray-900 font-semibold">
                                macworks
                              </span>
                            </a>
                          </div>

                          <span className="text-gray-700">posted</span>

                          <span className="text-gray-700">9 years ago</span>
                        </div>
                      </div>

                      <div className="flex flex-wrap gap-2 mt-2 lg:mt-0 lg:gap-x-4">
                        <a
                          href="https://laravel.io/forum/tags/testing"
                          className="flex gap-2"
                        >
                          <span className="inline-block text-sm text-gray-900 bg-gray-100 border border-gray-200 rounded py-1.5 px-3 leading-none">
                            Testing
                          </span>
                        </a>
                      </div>
                    </div>

                    <div className="mt-3 break-words">
                      <h3 className="text-xl text-gray-900 font-semibold">
                        <a
                          href="https://laravel.io/forum/10-26-2014-how-do-i-properly-mock-a-repository"
                          className="hover:underline"
                        >
                          How do I properly mock a repository?
                        </a>
                      </h3>

                      <p className="text-gray-800 leading-7 mt-1">
                        I've given up a couple times now but with a fresh night
                        of sleep I'm back at it because I'm determin...
                      </p>
                    </div>

                    <div className="flex justify-between items-center mt-4">
                      <div className="flex gap-x-5">
                        <span className="flex items-center gap-x-2">
                          <svg
                            className="w-6 h-6"
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke-width="1.5"
                            stroke="currentColor"
                            aria-hidden="true"
                          >
                            <path
                              stroke-linecap="round"
                              stroke-linejoin="round"
                              d="M6.633 10.5c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 012.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 00.322-1.672V3a.75.75 0 01.75-.75A2.25 2.25 0 0116.5 4.5c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 01-2.649 7.521c-.388.482-.987.729-1.605.729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 00-1.423-.23H5.904M14.25 9h2.25M5.904 18.75c.083.205.173.405.27.602.197.4-.078.898-.523.898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 01-.521-3.507c0-1.553.295-3.036.831-4.398C3.387 10.203 4.167 9.75 5 9.75h1.053c.472 0 .745.556.5.96a8.958 8.958 0 00-1.302 4.665c0 1.194.232 2.333.654 3.375z"
                            ></path>
                          </svg>{" "}
                          <span></span>
                          <span className="sr-only">Likes</span>
                        </span>

                        <span className="flex items-center gap-x-2">
                          <svg
                            className="w-6 h-6"
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke-width="1.5"
                            stroke="currentColor"
                            aria-hidden="true"
                          >
                            <path
                              stroke-linecap="round"
                              stroke-linejoin="round"
                              d="M20.25 8.511c.884.284 1.5 1.128 1.5 2.097v4.286c0 1.136-.847 2.1-1.98 2.193-.34.027-.68.052-1.02.072v3.091l-3-3c-1.354 0-2.694-.055-4.02-.163a2.115 2.115 0 01-.825-.242m9.345-8.334a2.126 2.126 0 00-.476-.095 48.64 48.64 0 00-8.048 0c-1.131.094-1.976 1.057-1.976 2.192v4.286c0 .837.46 1.58 1.155 1.951m9.345-8.334V6.637c0-1.621-1.152-3.026-2.76-3.235A48.455 48.455 0 0011.25 3c-2.115 0-4.198.137-6.24.402-1.608.209-2.76 1.614-2.76 3.235v6.226c0 1.621 1.152 3.026 2.76 3.235.577.075 1.157.14 1.74.194V21l4.155-4.155"
                            ></path>
                          </svg>{" "}
                          <span></span>
                          <span className="sr-only">Replies</span>
                        </span>
                      </div>

                      <a
                        href="https://laravel.io/forum/10-26-2014-how-do-i-properly-mock-a-repository#16086"
                        className="flex items-center gap-x-2 font-medium text-lio-500"
                      >
                        <svg
                          className="w-6 h-6"
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          stroke-width="1.5"
                          stroke="currentColor"
                          aria-hidden="true"
                        >
                          <path
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            d="M9 12.75L11.25 15 15 9.75M21 12c0 1.268-.63 2.39-1.593 3.068a3.745 3.745 0 01-1.043 3.296 3.745 3.745 0 01-3.296 1.043A3.745 3.745 0 0112 21c-1.268 0-2.39-.63-3.068-1.593a3.746 3.746 0 01-3.296-1.043 3.745 3.745 0 01-1.043-3.296A3.745 3.745 0 013 12c0-1.268.63-2.39 1.593-3.068a3.745 3.745 0 011.043-3.296 3.746 3.746 0 013.296-1.043A3.746 3.746 0 0112 3c1.268 0 2.39.63 3.068 1.593a3.746 3.746 0 013.296 1.043 3.746 3.746 0 011.043 3.296A3.745 3.745 0 0121 12z"
                          ></path>
                        </svg>{" "}
                        <span className="hover:underline">Solved</span>
                      </a>
                    </div>
                  </div>
                  <div className="h-full rounded shadow-lg p-5 bg-white">
                    <div className="flex flex-col lg:flex-row lg:justify-between lg:items-center">
                      <div>
                        <div className="flex flex-wrap items-center space-x-1 text-sm">
                          <div className="flex items-center">
                            <a href="https://laravel.io/user/macworks">
                              <Image
                                src={person}
                                className="bg-gray-50 rounded-full w-6 h-6 mr-2"
                              />
                            </a>

                            <a
                              href="https://laravel.io/user/macworks"
                              className="hover:underline"
                            >
                              <span className="text-gray-900 font-semibold">
                                macworks
                              </span>
                            </a>
                          </div>

                          <span className="text-gray-700">posted</span>

                          <span className="text-gray-700">9 years ago</span>
                        </div>
                      </div>

                      <div className="flex flex-wrap gap-2 mt-2 lg:mt-0 lg:gap-x-4">
                        <a
                          href="https://laravel.io/forum/tags/configuration"
                          className="flex gap-2"
                        >
                          <span className="inline-block text-sm text-gray-900 bg-gray-100 border border-gray-200 rounded py-1.5 px-3 leading-none">
                            Configuration
                          </span>
                        </a>
                        <a
                          href="https://laravel.io/forum/tags/testing"
                          className="flex gap-2"
                        >
                          <span className="inline-block text-sm text-gray-900 bg-gray-100 border border-gray-200 rounded py-1.5 px-3 leading-none">
                            Testing
                          </span>
                        </a>
                      </div>
                    </div>

                    <div className="mt-3 break-words">
                      <h3 className="text-xl text-gray-900 font-semibold">
                        <a
                          href="https://laravel.io/forum/10-25-2014-trying-to-learn-tdd"
                          className="hover:underline"
                        >
                          Trying to learn TDD
                        </a>
                      </h3>

                      <p className="text-gray-800 leading-7 mt-1">
                        I'm reading through Jeffery Way's book "Laravel Testing
                        Decoded" and I've run into a snag....
                      </p>
                    </div>

                    <div className="flex justify-between items-center mt-4">
                      <div className="flex gap-x-5">
                        <span className="flex items-center gap-x-2">
                          <svg
                            className="w-6 h-6"
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke-width="1.5"
                            stroke="currentColor"
                            aria-hidden="true"
                          >
                            <path
                              stroke-linecap="round"
                              stroke-linejoin="round"
                              d="M6.633 10.5c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 012.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 00.322-1.672V3a.75.75 0 01.75-.75A2.25 2.25 0 0116.5 4.5c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 01-2.649 7.521c-.388.482-.987.729-1.605.729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 00-1.423-.23H5.904M14.25 9h2.25M5.904 18.75c.083.205.173.405.27.602.197.4-.078.898-.523.898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 01-.521-3.507c0-1.553.295-3.036.831-4.398C3.387 10.203 4.167 9.75 5 9.75h1.053c.472 0 .745.556.5.96a8.958 8.958 0 00-1.302 4.665c0 1.194.232 2.333.654 3.375z"
                            ></path>
                          </svg>{" "}
                          <span></span>
                          <span className="sr-only">Likes</span>
                        </span>

                        <span className="flex items-center gap-x-2">
                          <svg
                            className="w-6 h-6"
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke-width="1.5"
                            stroke="currentColor"
                            aria-hidden="true"
                          >
                            <path
                              stroke-linecap="round"
                              stroke-linejoin="round"
                              d="M20.25 8.511c.884.284 1.5 1.128 1.5 2.097v4.286c0 1.136-.847 2.1-1.98 2.193-.34.027-.68.052-1.02.072v3.091l-3-3c-1.354 0-2.694-.055-4.02-.163a2.115 2.115 0 01-.825-.242m9.345-8.334a2.126 2.126 0 00-.476-.095 48.64 48.64 0 00-8.048 0c-1.131.094-1.976 1.057-1.976 2.192v4.286c0 .837.46 1.58 1.155 1.951m9.345-8.334V6.637c0-1.621-1.152-3.026-2.76-3.235A48.455 48.455 0 0011.25 3c-2.115 0-4.198.137-6.24.402-1.608.209-2.76 1.614-2.76 3.235v6.226c0 1.621 1.152 3.026 2.76 3.235.577.075 1.157.14 1.74.194V21l4.155-4.155"
                            ></path>
                          </svg>{" "}
                          <span></span>
                          <span className="sr-only">Replies</span>
                        </span>
                      </div>
                    </div>
                  </div>
                  <div className="h-full rounded shadow-lg p-5 bg-white">
                    <div className="flex flex-col lg:flex-row lg:justify-between lg:items-center">
                      <div>
                        <div className="flex flex-wrap items-center space-x-1 text-sm">
                          <div className="flex items-center">
                            <a href="https://laravel.io/user/macworks">
                              <Image
                                src={person}
                                className="bg-gray-50 rounded-full w-6 h-6 mr-2"
                              />
                            </a>

                            <a
                              href="https://laravel.io/user/macworks"
                              className="hover:underline"
                            >
                              <span className="text-gray-900 font-semibold">
                                macworks
                              </span>
                            </a>
                          </div>

                          <span className="text-gray-700">posted</span>

                          <span className="text-gray-700">9 years ago</span>
                        </div>
                      </div>

                      <div className="flex flex-wrap gap-2 mt-2 lg:mt-0 lg:gap-x-4">
                        <a
                          href="https://laravel.io/forum/tags/testing"
                          className="flex gap-2"
                        >
                          <span className="inline-block text-sm text-gray-900 bg-gray-100 border border-gray-200 rounded py-1.5 px-3 leading-none">
                            Testing
                          </span>
                        </a>
                      </div>
                    </div>

                    <div className="mt-3 break-words">
                      <h3 className="text-xl text-gray-900 font-semibold">
                        <a
                          href="https://laravel.io/forum/10-25-2014-could-not-load-guardphpunit"
                          className="hover:underline"
                        >
                          Could not load 'guard/phpunit'
                        </a>
                      </h3>

                      <p className="text-gray-800 leading-7 mt-1">
                        I am following along with Jeffery Way's book Laravel
                        Testing Decoded. In chapter 4 he outlines insta...
                      </p>
                    </div>

                    <div className="flex justify-between items-center mt-4">
                      <div className="flex gap-x-5">
                        <span className="flex items-center gap-x-2">
                          <svg
                            className="w-6 h-6"
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke-width="1.5"
                            stroke="currentColor"
                            aria-hidden="true"
                          >
                            <path
                              stroke-linecap="round"
                              stroke-linejoin="round"
                              d="M6.633 10.5c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 012.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 00.322-1.672V3a.75.75 0 01.75-.75A2.25 2.25 0 0116.5 4.5c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 01-2.649 7.521c-.388.482-.987.729-1.605.729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 00-1.423-.23H5.904M14.25 9h2.25M5.904 18.75c.083.205.173.405.27.602.197.4-.078.898-.523.898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 01-.521-3.507c0-1.553.295-3.036.831-4.398C3.387 10.203 4.167 9.75 5 9.75h1.053c.472 0 .745.556.5.96a8.958 8.958 0 00-1.302 4.665c0 1.194.232 2.333.654 3.375z"
                            ></path>
                          </svg>{" "}
                          <span></span>
                          <span className="sr-only">Likes</span>
                        </span>

                        <span className="flex items-center gap-x-2">
                          <svg
                            className="w-6 h-6"
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke-width="1.5"
                            stroke="currentColor"
                            aria-hidden="true"
                          >
                            <path
                              stroke-linecap="round"
                              stroke-linejoin="round"
                              d="M20.25 8.511c.884.284 1.5 1.128 1.5 2.097v4.286c0 1.136-.847 2.1-1.98 2.193-.34.027-.68.052-1.02.072v3.091l-3-3c-1.354 0-2.694-.055-4.02-.163a2.115 2.115 0 01-.825-.242m9.345-8.334a2.126 2.126 0 00-.476-.095 48.64 48.64 0 00-8.048 0c-1.131.094-1.976 1.057-1.976 2.192v4.286c0 .837.46 1.58 1.155 1.951m9.345-8.334V6.637c0-1.621-1.152-3.026-2.76-3.235A48.455 48.455 0 0011.25 3c-2.115 0-4.198.137-6.24.402-1.608.209-2.76 1.614-2.76 3.235v6.226c0 1.621 1.152 3.026 2.76 3.235.577.075 1.157.14 1.74.194V21l4.155-4.155"
                            ></path>
                          </svg>{" "}
                          <span></span>
                          <span className="sr-only">Replies</span>
                        </span>
                      </div>

                      <a
                        href="https://laravel.io/forum/10-25-2014-could-not-load-guardphpunit#17424"
                        className="flex items-center gap-x-2 font-medium text-lio-500"
                      >
                        <svg
                          className="w-6 h-6"
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          stroke-width="1.5"
                          stroke="currentColor"
                          aria-hidden="true"
                        >
                          <path
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            d="M9 12.75L11.25 15 15 9.75M21 12c0 1.268-.63 2.39-1.593 3.068a3.745 3.745 0 01-1.043 3.296 3.745 3.745 0 01-3.296 1.043A3.745 3.745 0 0112 21c-1.268 0-2.39-.63-3.068-1.593a3.746 3.746 0 01-3.296-1.043 3.745 3.745 0 01-1.043-3.296A3.745 3.745 0 013 12c0-1.268.63-2.39 1.593-3.068a3.745 3.745 0 011.043-3.296 3.746 3.746 0 013.296-1.043A3.746 3.746 0 0112 3c1.268 0 2.39.63 3.068 1.593a3.746 3.746 0 013.296 1.043 3.746 3.746 0 011.043 3.296A3.745 3.745 0 0121 12z"
                          ></path>
                        </svg>{" "}
                        <span className="hover:underline">Solved</span>
                      </a>
                    </div>
                  </div>
                  <div className="h-full rounded shadow-lg p-5 bg-white">
                    <div className="flex flex-col lg:flex-row lg:justify-between lg:items-center">
                      <div>
                        <div className="flex flex-wrap items-center space-x-1 text-sm">
                          <div className="flex items-center">
                            <a href="https://laravel.io/user/macworks">
                              <Image
                                src={person}
                                className="bg-gray-50 rounded-full w-6 h-6 mr-2"
                              />
                            </a>

                            <a
                              href="https://laravel.io/user/macworks"
                              className="hover:underline"
                            >
                              <span className="text-gray-900 font-semibold">
                                macworks
                              </span>
                            </a>
                          </div>

                          <span className="text-gray-700">posted</span>

                          <span className="text-gray-700">9 years ago</span>
                        </div>
                      </div>

                      <div className="flex flex-wrap gap-2 mt-2 lg:mt-0 lg:gap-x-4">
                        <a
                          href="https://laravel.io/forum/tags/blade"
                          className="flex gap-2"
                        >
                          <span className="inline-block text-sm text-gray-900 bg-gray-100 border border-gray-200 rounded py-1.5 px-3 leading-none">
                            Blade
                          </span>
                        </a>
                        <a
                          href="https://laravel.io/forum/tags/mail"
                          className="flex gap-2"
                        >
                          <span className="inline-block text-sm text-gray-900 bg-gray-100 border border-gray-200 rounded py-1.5 px-3 leading-none">
                            Mail
                          </span>
                        </a>
                      </div>
                    </div>

                    <div className="mt-3 break-words">
                      <h3 className="text-xl text-gray-900 font-semibold">
                        <a
                          href="https://laravel.io/forum/09-04-2014-plain-text-email-line-breaks"
                          className="hover:underline"
                        >
                          Plain Text Email &amp; Line Breaks
                        </a>
                      </h3>

                      <p className="text-gray-800 leading-7 mt-1">
                        How does one add a line break to the plain text version
                        of an email message when using a blade templ...
                      </p>
                    </div>

                    <div className="flex justify-between items-center mt-4">
                      <div className="flex gap-x-5">
                        <span className="flex items-center gap-x-2">
                          <svg
                            className="w-6 h-6"
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke-width="1.5"
                            stroke="currentColor"
                            aria-hidden="true"
                          >
                            <path
                              stroke-linecap="round"
                              stroke-linejoin="round"
                              d="M6.633 10.5c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 012.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 00.322-1.672V3a.75.75 0 01.75-.75A2.25 2.25 0 0116.5 4.5c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 01-2.649 7.521c-.388.482-.987.729-1.605.729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 00-1.423-.23H5.904M14.25 9h2.25M5.904 18.75c.083.205.173.405.27.602.197.4-.078.898-.523.898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 01-.521-3.507c0-1.553.295-3.036.831-4.398C3.387 10.203 4.167 9.75 5 9.75h1.053c.472 0 .745.556.5.96a8.958 8.958 0 00-1.302 4.665c0 1.194.232 2.333.654 3.375z"
                            ></path>
                          </svg>{" "}
                          <span></span>
                          <span className="sr-only">Likes</span>
                        </span>

                        <span className="flex items-center gap-x-2">
                          <svg
                            className="w-6 h-6"
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke-width="1.5"
                            stroke="currentColor"
                            aria-hidden="true"
                          >
                            <path
                              stroke-linecap="round"
                              stroke-linejoin="round"
                              d="M20.25 8.511c.884.284 1.5 1.128 1.5 2.097v4.286c0 1.136-.847 2.1-1.98 2.193-.34.027-.68.052-1.02.072v3.091l-3-3c-1.354 0-2.694-.055-4.02-.163a2.115 2.115 0 01-.825-.242m9.345-8.334a2.126 2.126 0 00-.476-.095 48.64 48.64 0 00-8.048 0c-1.131.094-1.976 1.057-1.976 2.192v4.286c0 .837.46 1.58 1.155 1.951m9.345-8.334V6.637c0-1.621-1.152-3.026-2.76-3.235A48.455 48.455 0 0011.25 3c-2.115 0-4.198.137-6.24.402-1.608.209-2.76 1.614-2.76 3.235v6.226c0 1.621 1.152 3.026 2.76 3.235.577.075 1.157.14 1.74.194V21l4.155-4.155"
                            ></path>
                          </svg>{" "}
                          <span></span>
                          <span className="sr-only">Replies</span>
                        </span>
                      </div>

                      <a
                        href="https://laravel.io/forum/09-04-2014-plain-text-email-line-breaks#13608"
                        className="flex items-center gap-x-2 font-medium text-lio-500"
                      >
                        <svg
                          className="w-6 h-6"
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          stroke-width="1.5"
                          stroke="currentColor"
                          aria-hidden="true"
                        >
                          <path
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            d="M9 12.75L11.25 15 15 9.75M21 12c0 1.268-.63 2.39-1.593 3.068a3.745 3.745 0 01-1.043 3.296 3.745 3.745 0 01-3.296 1.043A3.745 3.745 0 0112 21c-1.268 0-2.39-.63-3.068-1.593a3.746 3.746 0 01-3.296-1.043 3.745 3.745 0 01-1.043-3.296A3.745 3.745 0 013 12c0-1.268.63-2.39 1.593-3.068a3.745 3.745 0 011.043-3.296 3.746 3.746 0 013.296-1.043A3.746 3.746 0 0112 3c1.268 0 2.39.63 3.068 1.593a3.746 3.746 0 013.296 1.043 3.746 3.746 0 011.043 3.296A3.745 3.745 0 0121 12z"
                          ></path>
                        </svg>{" "}
                        <span className="hover:underline">Solved</span>
                      </a>
                    </div>
                  </div>
                  <div className="h-full rounded shadow-lg p-5 bg-white">
                    <div className="flex flex-col lg:flex-row lg:justify-between lg:items-center">
                      <div>
                        <div className="flex flex-wrap items-center space-x-1 text-sm">
                          <div className="flex items-center">
                            <a href="https://laravel.io/user/macworks">
                              <Image
                                src={person}
                                className="bg-gray-50 rounded-full w-6 h-6 mr-2"
                              />
                            </a>

                            <a
                              href="https://laravel.io/user/macworks"
                              className="hover:underline"
                            >
                              <span className="text-gray-900 font-semibold">
                                macworks
                              </span>
                            </a>
                          </div>

                          <span className="text-gray-700">posted</span>

                          <span className="text-gray-700">9 years ago</span>
                        </div>
                      </div>

                      <div className="flex flex-wrap gap-2 mt-2 lg:mt-0 lg:gap-x-4">
                        <a
                          href="https://laravel.io/forum/tags/requests"
                          className="flex gap-2"
                        >
                          <span className="inline-block text-sm text-gray-900 bg-gray-100 border border-gray-200 rounded py-1.5 px-3 leading-none">
                            Requests
                          </span>
                        </a>
                      </div>
                    </div>

                    <div className="mt-3 break-words">
                      <h3 className="text-xl text-gray-900 font-semibold">
                        <a
                          href="https://laravel.io/forum/03-07-2014-nested-route-groups"
                          className="hover:underline"
                        >
                          Nested route groups
                        </a>
                      </h3>

                      <p className="text-gray-800 leading-7 mt-1">
                        How do I nest route groups? I'm on 4.1.23 and when I
                        attempt to nest route groups I get an "arr...
                      </p>
                    </div>

                    <div className="flex justify-between items-center mt-4">
                      <div className="flex gap-x-5">
                        <span className="flex items-center gap-x-2">
                          <svg
                            className="w-6 h-6"
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke-width="1.5"
                            stroke="currentColor"
                            aria-hidden="true"
                          >
                            <path
                              stroke-linecap="round"
                              stroke-linejoin="round"
                              d="M6.633 10.5c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 012.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 00.322-1.672V3a.75.75 0 01.75-.75A2.25 2.25 0 0116.5 4.5c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 01-2.649 7.521c-.388.482-.987.729-1.605.729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 00-1.423-.23H5.904M14.25 9h2.25M5.904 18.75c.083.205.173.405.27.602.197.4-.078.898-.523.898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 01-.521-3.507c0-1.553.295-3.036.831-4.398C3.387 10.203 4.167 9.75 5 9.75h1.053c.472 0 .745.556.5.96a8.958 8.958 0 00-1.302 4.665c0 1.194.232 2.333.654 3.375z"
                            ></path>
                          </svg>{" "}
                          <span></span>
                          <span className="sr-only">Likes</span>
                        </span>

                        <span className="flex items-center gap-x-2">
                          <svg
                            className="w-6 h-6"
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke-width="1.5"
                            stroke="currentColor"
                            aria-hidden="true"
                          >
                            <path
                              stroke-linecap="round"
                              stroke-linejoin="round"
                              d="M20.25 8.511c.884.284 1.5 1.128 1.5 2.097v4.286c0 1.136-.847 2.1-1.98 2.193-.34.027-.68.052-1.02.072v3.091l-3-3c-1.354 0-2.694-.055-4.02-.163a2.115 2.115 0 01-.825-.242m9.345-8.334a2.126 2.126 0 00-.476-.095 48.64 48.64 0 00-8.048 0c-1.131.094-1.976 1.057-1.976 2.192v4.286c0 .837.46 1.58 1.155 1.951m9.345-8.334V6.637c0-1.621-1.152-3.026-2.76-3.235A48.455 48.455 0 0011.25 3c-2.115 0-4.198.137-6.24.402-1.608.209-2.76 1.614-2.76 3.235v6.226c0 1.621 1.152 3.026 2.76 3.235.577.075 1.157.14 1.74.194V21l4.155-4.155"
                            ></path>
                          </svg>{" "}
                          <span></span>
                          <span className="sr-only">Replies</span>
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div x-show="tab === &#39;replies&#39;">
                <div className="flex flex-col gap-y-6">
                  <div className="h-full rounded shadow-lg p-5 bg-white">
                    <div className="flex flex-col lg:flex-row lg:justify-between lg:items-center">
                      <div>
                        <div className="flex flex-wrap items-center space-x-1 text-sm">
                          <div className="flex items-center">
                            <a href="https://laravel.io/user/macworks">
                              <Image
                                src={person}
                                className="bg-gray-50 rounded-full w-6 h-6 mr-2"
                              />
                            </a>

                            <a
                              href="https://laravel.io/user/macworks"
                              className="hover:underline"
                            >
                              <span className="text-gray-900 font-semibold">
                                macworks
                              </span>
                            </a>
                          </div>

                          <span className="text-gray-700">replied</span>

                          <span className="text-gray-700">7 years ago</span>
                        </div>
                      </div>
                    </div>

                    <div className="mt-3 break-words">
                      <a
                        href="https://laravel.io/forum/02-04-2016-advanced-relationship"
                        className="hover:underline"
                      >
                        <h3 className="text-xl text-gray-900 font-semibold">
                          Advanced relationship
                        </h3>
                      </a>

                      <p className="text-gray-800 leading-7 mt-1">
                        I have a similar situation where I have users, I have
                        accounts and I have roles. You can simply swap...
                      </p>
                    </div>

                    <div className="flex justify-between items-center mt-4">
                      <div className="flex gap-x-5">
                        <span className="flex items-center gap-x-2">
                          <svg
                            className="w-6 h-6"
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke-width="1.5"
                            stroke="currentColor"
                            aria-hidden="true"
                          >
                            <path
                              stroke-linecap="round"
                              stroke-linejoin="round"
                              d="M6.633 10.5c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 012.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 00.322-1.672V3a.75.75 0 01.75-.75A2.25 2.25 0 0116.5 4.5c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 01-2.649 7.521c-.388.482-.987.729-1.605.729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 00-1.423-.23H5.904M14.25 9h2.25M5.904 18.75c.083.205.173.405.27.602.197.4-.078.898-.523.898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 01-.521-3.507c0-1.553.295-3.036.831-4.398C3.387 10.203 4.167 9.75 5 9.75h1.053c.472 0 .745.556.5.96a8.958 8.958 0 00-1.302 4.665c0 1.194.232 2.333.654 3.375z"
                            ></path>
                          </svg>{" "}
                          <span>0</span>
                          <span className="sr-only">Likes</span>
                        </span>
                      </div>
                    </div>
                  </div>
                  <div className="h-full rounded shadow-lg p-5 bg-white">
                    <div className="flex flex-col lg:flex-row lg:justify-between lg:items-center">
                      <div>
                        <div className="flex flex-wrap items-center space-x-1 text-sm">
                          <div className="flex items-center">
                            <a href="https://laravel.io/user/macworks">
                              <Image
                                src={person}
                                className="bg-gray-50 rounded-full w-6 h-6 mr-2"
                              />
                            </a>

                            <a
                              href="https://laravel.io/user/macworks"
                              className="hover:underline"
                            >
                              <span className="text-gray-900 font-semibold">
                                macworks
                              </span>
                            </a>
                          </div>

                          <span className="text-gray-700">replied</span>

                          <span className="text-gray-700">8 years ago</span>
                        </div>
                      </div>
                    </div>

                    <div className="mt-3 break-words">
                      <a
                        href="https://laravel.io/forum/10-25-2014-could-not-load-guardphpunit"
                        className="hover:underline"
                      >
                        <h3 className="text-xl text-gray-900 font-semibold">
                          Could not load 'guard/phpunit'
                        </h3>
                      </a>

                      <p className="text-gray-800 leading-7 mt-1">
                        iovino: Thanks for the solution. Works for me ... except
                        terminal-notifier doesn't seem to work.
                      </p>
                    </div>

                    <div className="flex justify-between items-center mt-4">
                      <div className="flex gap-x-5">
                        <span className="flex items-center gap-x-2">
                          <svg
                            className="w-6 h-6"
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke-width="1.5"
                            stroke="currentColor"
                            aria-hidden="true"
                          >
                            <path
                              stroke-linecap="round"
                              stroke-linejoin="round"
                              d="M6.633 10.5c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 012.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 00.322-1.672V3a.75.75 0 01.75-.75A2.25 2.25 0 0116.5 4.5c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 01-2.649 7.521c-.388.482-.987.729-1.605.729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 00-1.423-.23H5.904M14.25 9h2.25M5.904 18.75c.083.205.173.405.27.602.197.4-.078.898-.523.898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 01-.521-3.507c0-1.553.295-3.036.831-4.398C3.387 10.203 4.167 9.75 5 9.75h1.053c.472 0 .745.556.5.96a8.958 8.958 0 00-1.302 4.665c0 1.194.232 2.333.654 3.375z"
                            ></path>
                          </svg>{" "}
                          <span>0</span>
                          <span className="sr-only">Likes</span>
                        </span>
                      </div>
                    </div>
                  </div>
                  <div className="h-full rounded shadow-lg p-5 bg-white">
                    <div className="flex flex-col lg:flex-row lg:justify-between lg:items-center">
                      <div>
                        <div className="flex flex-wrap items-center space-x-1 text-sm">
                          <div className="flex items-center">
                            <a href="https://laravel.io/user/macworks">
                              <Image
                                src={person}
                                className="bg-gray-50 rounded-full w-6 h-6 mr-2"
                              />
                            </a>

                            <a
                              href="https://laravel.io/user/macworks"
                              className="hover:underline"
                            >
                              <span className="text-gray-900 font-semibold">
                                macworks
                              </span>
                            </a>
                          </div>

                          <span className="text-gray-700">replied</span>

                          <span className="text-gray-700">8 years ago</span>
                        </div>
                      </div>
                    </div>

                    <div className="mt-3 break-words">
                      <a
                        href="https://laravel.io/forum/07-29-2014-unit-testing-phpunit-command-doesnt-exists"
                        className="hover:underline"
                      >
                        <h3 className="text-xl text-gray-900 font-semibold">
                          Unit testing : Phpunit command doesn't exists
                        </h3>
                      </a>

                      <p className="text-gray-800 leading-7 mt-1">
                        I ran into this today. I don't know what changed, I was
                        able to run phpunit from my project root jus...
                      </p>
                    </div>

                    <div className="flex justify-between items-center mt-4">
                      <div className="flex gap-x-5">
                        <span className="flex items-center gap-x-2">
                          <svg
                            className="w-6 h-6"
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke-width="1.5"
                            stroke="currentColor"
                            aria-hidden="true"
                          >
                            <path
                              stroke-linecap="round"
                              stroke-linejoin="round"
                              d="M6.633 10.5c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 012.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 00.322-1.672V3a.75.75 0 01.75-.75A2.25 2.25 0 0116.5 4.5c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 01-2.649 7.521c-.388.482-.987.729-1.605.729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 00-1.423-.23H5.904M14.25 9h2.25M5.904 18.75c.083.205.173.405.27.602.197.4-.078.898-.523.898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 01-.521-3.507c0-1.553.295-3.036.831-4.398C3.387 10.203 4.167 9.75 5 9.75h1.053c.472 0 .745.556.5.96a8.958 8.958 0 00-1.302 4.665c0 1.194.232 2.333.654 3.375z"
                            ></path>
                          </svg>{" "}
                          <span>0</span>
                          <span className="sr-only">Likes</span>
                        </span>
                      </div>
                    </div>
                  </div>
                  <div className="h-full rounded shadow-lg p-5 bg-white">
                    <div className="flex flex-col lg:flex-row lg:justify-between lg:items-center">
                      <div>
                        <div className="flex flex-wrap items-center space-x-1 text-sm">
                          <div className="flex items-center">
                            <a href="https://laravel.io/user/macworks">
                              <Image
                                src={person}
                                className="bg-gray-50 rounded-full w-6 h-6 mr-2"
                              />
                            </a>

                            <a
                              href="https://laravel.io/user/macworks"
                              className="hover:underline"
                            >
                              <span className="text-gray-900 font-semibold">
                                macworks
                              </span>
                            </a>
                          </div>

                          <span className="text-gray-700">replied</span>

                          <span className="text-gray-700">8 years ago</span>
                        </div>
                      </div>
                    </div>

                    <div className="mt-3 break-words">
                      <a
                        href="https://laravel.io/forum/05-06-2015-laravel-5-authentication-changing-user-namespace"
                        className="hover:underline"
                      >
                        <h3 className="text-xl text-gray-900 font-semibold">
                          Laravel 5 Authentication - Changing User Namespace?
                        </h3>
                      </a>

                      <p className="text-gray-800 leading-7 mt-1">
                        I'm not sure if this is related or not but I recently
                        began the process of migrating my app to L5 an...
                      </p>
                    </div>

                    <div className="flex justify-between items-center mt-4">
                      <div className="flex gap-x-5">
                        <span className="flex items-center gap-x-2">
                          <svg
                            className="w-6 h-6"
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke-width="1.5"
                            stroke="currentColor"
                            aria-hidden="true"
                          >
                            <path
                              stroke-linecap="round"
                              stroke-linejoin="round"
                              d="M6.633 10.5c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 012.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 00.322-1.672V3a.75.75 0 01.75-.75A2.25 2.25 0 0116.5 4.5c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 01-2.649 7.521c-.388.482-.987.729-1.605.729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 00-1.423-.23H5.904M14.25 9h2.25M5.904 18.75c.083.205.173.405.27.602.197.4-.078.898-.523.898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 01-.521-3.507c0-1.553.295-3.036.831-4.398C3.387 10.203 4.167 9.75 5 9.75h1.053c.472 0 .745.556.5.96a8.958 8.958 0 00-1.302 4.665c0 1.194.232 2.333.654 3.375z"
                            ></path>
                          </svg>{" "}
                          <span>0</span>
                          <span className="sr-only">Likes</span>
                        </span>
                      </div>
                    </div>
                  </div>
                  <div className="h-full rounded shadow-lg p-5 bg-white">
                    <div className="flex flex-col lg:flex-row lg:justify-between lg:items-center">
                      <div>
                        <div className="flex flex-wrap items-center space-x-1 text-sm">
                          <div className="flex items-center">
                            <a href="https://laravel.io/user/macworks">
                              <Image
                                src={person}
                                className="bg-gray-50 rounded-full w-6 h-6 mr-2"
                              />
                            </a>

                            <a
                              href="https://laravel.io/user/macworks"
                              className="hover:underline"
                            >
                              <span className="text-gray-900 font-semibold">
                                macworks
                              </span>
                            </a>
                          </div>

                          <span className="text-gray-700">replied</span>

                          <span className="text-gray-700">9 years ago</span>
                        </div>
                      </div>
                    </div>

                    <div className="mt-3 break-words">
                      <a
                        href="https://laravel.io/forum/10-26-2014-how-do-i-properly-mock-a-repository"
                        className="hover:underline"
                      >
                        <h3 className="text-xl text-gray-900 font-semibold">
                          How do I properly mock a repository?
                        </h3>
                      </a>

                      <p className="text-gray-800 leading-7 mt-1">
                        I found the answer here ...
                        https://laracasts.com/discuss/channels/general-discussion/mockery-error?...
                      </p>
                    </div>

                    <div className="flex justify-between items-center mt-4">
                      <div className="flex gap-x-5">
                        <span className="flex items-center gap-x-2">
                          <svg
                            className="w-6 h-6"
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke-width="1.5"
                            stroke="currentColor"
                            aria-hidden="true"
                          >
                            <path
                              stroke-linecap="round"
                              stroke-linejoin="round"
                              d="M6.633 10.5c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 012.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 00.322-1.672V3a.75.75 0 01.75-.75A2.25 2.25 0 0116.5 4.5c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 01-2.649 7.521c-.388.482-.987.729-1.605.729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 00-1.423-.23H5.904M14.25 9h2.25M5.904 18.75c.083.205.173.405.27.602.197.4-.078.898-.523.898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 01-.521-3.507c0-1.553.295-3.036.831-4.398C3.387 10.203 4.167 9.75 5 9.75h1.053c.472 0 .745.556.5.96a8.958 8.958 0 00-1.302 4.665c0 1.194.232 2.333.654 3.375z"
                            ></path>
                          </svg>{" "}
                          <span>0</span>
                          <span className="sr-only">Likes</span>
                        </span>
                      </div>

                      <span className="flex items-center gap-x-2 font-medium text-lio-500">
                        <svg
                          className="w-6 h-6"
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          stroke-width="1.5"
                          stroke="currentColor"
                          aria-hidden="true"
                        >
                          <path
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            d="M9 12.75L11.25 15 15 9.75M21 12c0 1.268-.63 2.39-1.593 3.068a3.745 3.745 0 01-1.043 3.296 3.745 3.745 0 01-3.296 1.043A3.745 3.745 0 0112 21c-1.268 0-2.39-.63-3.068-1.593a3.746 3.746 0 01-3.296-1.043 3.745 3.745 0 01-1.043-3.296A3.745 3.745 0 013 12c0-1.268.63-2.39 1.593-3.068a3.745 3.745 0 011.043-3.296 3.746 3.746 0 013.296-1.043A3.746 3.746 0 0112 3c1.268 0 2.39.63 3.068 1.593a3.746 3.746 0 013.296 1.043 3.746 3.746 0 011.043 3.296A3.745 3.745 0 0121 12z"
                          ></path>
                        </svg>{" "}
                        <span className="hover:underline">Solved</span>
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
}
