import React, { useEffect, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Report from "@/components/Report";
import Comment from "@/components/Comment";
import GoTop from "@/components/GoTop";

import mine from "@/img/mine.jpg";
import lastofus2 from "@/img/lastofus2.jpg";
import godofwar from "@/img/godofwar.jpg";

import { Help } from "@/components/Help";
import Breadcrumb from "@/components/Breadcrumb";
import Tags from "@/components/Tags";
import Author from "@/components/Author";
import RelatedNews from "@/components/RelatedNews";

export default function Detail() {
  const [reportModalOpen, setReportModalOpen] = useState(false);
  //   useEffect(() => {
  //     window.scrollTo(0, 0);
  //   }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <GoTop />
      <div className="flex mx-auto w-full pt-16 pb-2 px-4 bg-[#f6f8f7]">
        <div className="flex justify-center items-center w-full bg-green-100 h-20">
          <div className="text-gray-500">advertising</div>
        </div>
      </div>
      <section className="bg-[#f6f8f7] mt-2 md:mt-0 px-2">
        <div className="container w-full md:max-w-3xl mx-auto pt-4 md:pt-4 px-2 md:px-6">
          {/* breadcrumb */}
          <Breadcrumb />
          <div className="flex flex-col py-2 md:py-4">
            <span className="font-mabryblack uppercase leading-tight md:leading-11 text-2xl md:text-5xl pb-2 text-gray-900">
              Silent Hill 2 Remake Dev Bloober Team Giving Up Psychological
              Horror for 'Mass Market'
            </span>
            <div className="flex flex-col md:flex-row space-y-1 md:justify-between border-t-2 border-[#d54215] pt-2 md:pt-2">
              <span>
                <p className="text-sm md:text-sm font-mabry text-gray-900">
                  Published 19 February 2019
                </p>
              </span>
              <div className="font-mabry">
                <div className=" flex justify-between items-center text-base md:text-sm text-green-500 font-bold">
                  <div className="flex justify-end space-x-2">
                    <button>
                      <div className="flex rounded border py-1.5 px-2 shadow-menu border-gray-800 bg-[#1877f2] hover:bg-[#1877f2]  fill-[#1877f2] hover:fill-white  items-center justify-between md:space-x-1 hover:shadow-blue-500/50 ">
                        <span className="hidden md:block text-white font-mabrybold">
                          Facebook
                        </span>
                        <svg
                          className="w-5 h-5 md:w-4 md:h-4 text-white"
                          fill="currentColor"
                          viewBox="0 0 24 24"
                          aria-hidden="true"
                        >
                          <path
                            fillRule="evenodd"
                            d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z"
                            clipRule="evenodd"
                          ></path>
                        </svg>
                      </div>
                    </button>
                    <button>
                      <div className="flex rounded border py-1.5 px-2 shadow-menu border-gray-800 bg-[#1d9bf0] hover:bg-[#1d9bf0] fill-[#1d9bf0] hover:fill-white  items-center justify-between md:space-x-1 hover:shadow-sky-500/50">
                        <span className="hidden md:block text-white font-mabrybold">
                          Twitter
                        </span>
                        <svg
                          className="w-5 h-5 md:w-4 md:h-4 text-white"
                          fill="currentColor"
                          viewBox="0 0 24 24"
                          aria-hidden="true"
                        >
                          <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84"></path>
                        </svg>
                      </div>
                    </button>
                    <button>
                      <div className="flex rounded border py-1.5 px-2 shadow-menu border-gray-800 bg-gray-800 hover:bg-black  hover:fill-white  items-center justify-between md:space-x-1 hover:shadow-sky-500/50">
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          strokeWidth={1.5}
                          stroke="currentColor"
                          className="w-5 h-5 md:w-4 md:h-4 text-white"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            d="M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244"
                          />
                        </svg>

                        <span className="hidden md:block text-white font-mabry">
                          Copy url
                        </span>
                      </div>
                    </button>
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        setReportModalOpen(true);
                      }}
                    >
                      <div className="flex rounded border py-1.5 px-2 shadow-menu border-gray-800 bg-white hover:bg-white text-black hover:fill-white  items-center justify-between space-x-1 hover:shadow-sky-500/50">
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          viewBox="0 0 24 24"
                          fill="currentColor"
                          className="w-5 h-5 md:w-4 md:h-4"
                        >
                          <path
                            fillRule="evenodd"
                            d="M3 2.25a.75.75 0 01.75.75v.54l1.838-.46a9.75 9.75 0 016.725.738l.108.054a8.25 8.25 0 005.58.652l3.109-.732a.75.75 0 01.917.81 47.784 47.784 0 00.005 10.337.75.75 0 01-.574.812l-3.114.733a9.75 9.75 0 01-6.594-.77l-.108-.054a8.25 8.25 0 00-5.69-.625l-2.202.55V21a.75.75 0 01-1.5 0V3A.75.75 0 013 2.25z"
                            clipRule="evenodd"
                          />
                        </svg>

                        <span className="hidden md:block text-black font-mabry">
                          Report
                        </span>
                      </div>
                    </button>
                    <Report
                      modalOpen={reportModalOpen}
                      setModalOpen={setReportModalOpen}
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="absolute2 -z-10">
            <Image src={mine} quality={100} alt="" />
          </div>
          <div className="py-6 w-full text-lg text-gray-800 leading-normal">
            <div className="flex flex-col md:flex-row w-full md:space-x-3">
              <div className="w-full md:w-full">
                {/* CONTENT */}

                <div className="text-md font-mabry leading-snug">
                  <p className="md:py-3">
                    The upcoming film adaptation of Norman Reedus Walking Simulator - aka Death Stranding - has signed up arthouse darlings A24.
                  </p>

                  <p className="py-3">
                  As we first heard last year, the movie will be based on the debut release from Hideo Kojima’s post-Konami studio Kojima Productions. The game follows Norman Reedus’ Sam Porter Bridges as he trots his way across a very Iceland-looking North America with a massive stack of crates on his back and a baby in a jar on his front. Along the way he runs into Kojima’s rolodex of Hollywood buddies, including Guillermo Del Toro, Léa Seydoux and Mads Mikkelsen. There’s some stuff about setting up a nationwide W-Fi network, Troy Baker floating around in a skull mask and acid rain that summons inky ghosts.
                  </p>

                  <p className="py-3">
                  In fairness, that’s all a fairly good fit for A24, the studio behind more artsy, offbeat and eclectic fare such as Everything Everywhere All At Once, Hereditary, The Witch and The Whale, to name but a few.
                  </p>

                  <p className="py-3">
                  While Death Stranding is already packed with actors, don’t expect a direct adaptation - not least because it’d presumably be seven hours of Reedus grunting and picking up boxes he’s dropped. Echoing his past comments that “there's no real need" for straight video game-movie adaptations, the designer said that the Death Stranding film will aim for something that can only be done via film, rather than video games.
                  </p>
                  <p className="py-3">
                  “There are a lot of ‘game adaptation films’ out there but what we are creating is not just a direct translation of the game,” he said. “The intention is that our audience will not only be fans of the games, but our film will be for anyone who loves cinema.
                  </p>
                  <p className="py-3">
                  What we do know is that the film will share the video game’s exploration of the titular apocalyptic event which led to all the ghosts, beaches full of dead crabs and Geoff Keighley living in a random bunker somewhere.
                  </p>
                </div>

                <Help />

                <div className="md:text-sm text-gray-500 px-2 md:px-0 py-3 font-mabry">
                  Source:{" "}
                  <a
                    href="https://mydramalist.com/article/an-ultra-fan-guide-to-lee-elijah"
                    className="italic underline font-mabryitalic"
                  >
                    https://mydramalist.com/article/an-ultra-fan-guide-to-lee-elijah
                  </a>
                </div>

                {/* TAGS */}
                <Tags />
                {/* <hr className="border-b-2 border-gray-400 mb-8 mx-4" /> */}
                <Author />
                <Comment />
                {/* <hr className="border-b-2 border-gray-400 mb-8 mx-4" /> */}
              </div>
              {/* <div className="w-full md:w-1/3 bg-green-100">
                <div className="flex flex-col space-y-5">
                  <div className="rounded bg-white border border-gray-800 shadow-stack-sm group flex flex-col overflow-hidden hover:scale-105 ">
                    <a
                      href="https://statamic.com/blog/statamic-4-unleashed"
                      className="relative"
                    >
                      <Image src={lastofus2} alt="" className="w-full" />{" "}
                      <div className="absolute opacity-0 group-hover:opacity-75 z-20 inset-0 mix-blend-overlay w-full bg-gradient-to-br from-purple-hot to-teal"></div>
                    </a>{" "}
                    <div className="px-3 py-2 flex flex-col justify-between leading-tight">
                      <h3 className="font-mabrybold text-md">
                        <a href="https://statamic.com/blog/statamic-4-unleashed">
                          Statamic 4 Has Been Unleashed
                        </a>
                      </h3>{" "}
                      <div className="font-mabry text-xs">May 9th, 2023</div>
                    </div>
                  </div>
                  <div className="rounded bg-white border border-gray-800 shadow-stack-sm group flex flex-col overflow-hidden hover:scale-105 ">
                    <a
                      href="https://statamic.com/blog/statamic-4-unleashed"
                      className="relative"
                    >
                      <Image src={godofwar} alt="" className="w-full" />{" "}
                      <div className="absolute opacity-0 group-hover:opacity-75 z-20 inset-0 mix-blend-overlay w-full bg-gradient-to-br from-purple-hot to-teal"></div>
                    </a>{" "}
                    <div className="px-3 py-2 flex flex-col justify-between leading-tight">
                      <h3 className="font-mabrybold text-md">
                        <a href="https://statamic.com/blog/statamic-4-unleashed">
                          Statamic 4 Has Been Unleashed
                        </a>
                      </h3>{" "}
                      <div className="font-mabry text-xs">May 9th, 2023</div>
                    </div>
                  </div>
                </div>
              </div> */}
            </div>
          </div>
        </div>
      </section>
      <RelatedNews />
      <Footer />
    </>
  );
}
