import React, { useEffect } from "react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import Notice from "@/components/Notice";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import tournament from "@/img/tournament.jpg";
import festival from "@/img/festival.png";
import festival1 from "@/img/festival1.png";

export default function Detail() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Notice />

      <div className="h-max flex py-12 pb-20 px-20 bg-[#f2f2f2]">
        <div className="flex flex-col w-full mx-auto space-y-6 justify-center2 items-center">
          <div className="flex flex-col space-y-2">
            <span className="text-3xl font-mabryblack">
              Schedule Tournament
            </span>
            <span className="text-lg font-mabrybold leading-tight">
              See it all and immerse yourself in emotion – from the glee to the
              grit to the glory – at the 70th Sydney Film Festival this 7–18
              June 2023.
            </span>
          </div>

          <article>
            <div class="relative bg-purple-100 p-6 pl-8 rounded-lg md:p-8 md:pl-10 owl overflow-hidden">
              <div class="absolute w-2 h-full left-0 top-0 bottom-0 bg-purple-700 rounded-l"></div>{" "}
              <h3 class="max-w-lg text-purple-700 font-mabrybold text-2xl leading-tight">
                Talk about your latest project, the great tool you found or the
                problem you just solved recently?
              </h3>{" "}
              <ul class="py-4 pl-4 list-reset list-bullets list-disc font-mabry">
                <li>Talks are 15 minutes without Q&amp;A</li>{" "}
                <li>
                  We have <b>HDMI</b> &amp; <b>USB-C</b> available and the
                  resolution is 1080p (1920x1080)
                </li>
              </ul>{" "}
              <div>
                <a
                  href="https://docs.google.com/forms/d/e/1FAIpQLSfTaa-_wOFOQv3dZ7Ord9TJ3vN8wNdzUY5VQqzFiTg_WMQwEw/viewform?c=0&amp;w=1"
                  class=""
                >
                  <div class="bg-purple-800 hover:bg-purple-700 rounded-md font-mabry text-white inline-flex items-center h-10 px-4">
                    {" "}
                    <span>Submit your talk</span>{" "}
                  </div>
                </a>
              </div>
            </div>
          </article>
        </div>
      </div>
      <Footer />
    </>
  );
}
