import React from "react";
import Link from "next/link";
import Image from "next/image";
import Head from 'next/head'

import Header from '@/components/Header'
import Footer from '@/components/Footer'

import pencil from "@/img/home-pencil.svg";
import gem from "@/img/home-gem.svg";
import headphone from "@/img/home-headphones.svg";
import book from "@/img/home-book-green.svg";
import app from "@/img/home-app-yellow.svg";

import mine from "@/img/mine.jpg";
import fortnite from "@/img/fortnite.jpg";
import cyberpunk from "@/img/cyberpunk.jpg";

import minecraft from '@/img/mine.jpg'
import dingdong from '@/img/dingdong.jpg'

export default function News() {
  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div class="relative mt-12 block h-80 lg:col-span-2 lg:h-full">
          <Image
            src={dingdong}
            alt=""
            class="absolute inset-0 object-cover w-full h-full"
          />
        </div>
      <div className="h-max flex py-10 flex-col space-y-10 px-10 justify-center2 items-center2 bg-[#f4f4f0]">
        
        <div className="flex flex-row mx-auto w-3/4 space-x-6 justify-center2 items-center">
          <span className="text-3xl font-extrabold">Latest news</span>
        </div>

       
        {/* <section className="flex flex-row flex-wrap mx-auto w-3/4 justify-center2 items-center3">
          <div className="transition-all duration-150 flex w-full px-2 py-4 md:w-1/2 lg:w-1/3">
            <div className="relative flex flex-col border-2 border-gray-600 items-stretch min-h-full pb-4 mb-6 transition-all duration-150 bg-white rounded-lg shadow-lg hover:shadow-2xl">
              <div className="md:flex-shrink-0">
                <Image
                  src={mine}
                  className="object-fill w-full rounded-lg rounded-b-none "
                  alt=""
                />
              </div>

              <h1 className="px-4 pt-2 font-mabrybold font-bold">
                Lorem Ipsum dolor sit amet
              </h1>
              <div className="flex flex-row flex-wrap w-full h-40 px-4 py-2 overflow-hidden text-sm font-mabry leading-tight text-justify text-gray-700">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias,
                magni fugiat, odit incidunt necessitatibus aut nesciunt
                exercitationem aliquam id voluptatibus quisquam maiores officia
                sit amet accusantium aliquid quo obcaecati quasi.
              </div>
              <section className="absolute bottom-4 px-4 py-2 w-full ">
                <div className="flex w-full items-center justify-between space-x-2 ">
                  <div className="flex w-2/3 items-center justify-start ">
                    <img
                      className="object-cover h-8 rounded-full"
                      src="https://thumbs.dreamstime.com/b/default-avatar-photo-placeholder-profile-icon-eps-file-easy-to-edit-default-avatar-photo-placeholder-profile-icon-124557887.jpg"
                      alt="Avatar"
                    />
                    <div className="flex flex-col mx-2">
                      <a
                        href=""
                        className="font-semibold text-xs font-mabry text-gray-700 hover:underline"
                      >
                        Fajrian Aidil Pratama
                      </a>
                    </div>
                  </div>
                  <div className="flex w-1/3 justify-end text-xs font-mabry text-gray-600 ">
                    <span>9 minutes read</span>
                  </div>
                </div>
              </section>
            </div>
          </div>

          <div className="transition-all duration-150 flex w-full px-2 py-4 md:w-1/2 lg:w-1/3">
            <div className="relative flex flex-col border-2 border-gray-600 items-stretch min-h-full pb-4 mb-6 transition-all duration-150 bg-white rounded-lg shadow-lg hover:shadow-2xl">
              <div className="md:flex-shrink-0">
                <Image
                  src={cyberpunk}
                  className="object-fill w-full rounded-lg rounded-b-none"
                  alt=""
                />
              </div>

              <h1 className="px-4 pt-2 font-mabrybold font-bold">
                Lorem Ipsum dolor sit amet
              </h1>
              <div className="flex flex-row flex-wrap w-full h-40 px-4 py-2 overflow-hidden text-sm font-mabry leading-tight text-justify text-gray-700">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias,
                magni fugiat, odit incidunt necessitatibus aut nesciunt
                exercitationem aliquam id voluptatibus quisquam maiores officia
                sit amet accusantium aliquid quo obcaecati quasi.
              </div>
              <section className="absolute bottom-4  px-4 py-2 w-full ">
                <div className="flex w-full items-center justify-between space-x-2 ">
                  <div className="flex w-2/3 items-center justify-start ">
                    <img
                      className="object-cover h-8 rounded-full"
                      src="https://thumbs.dreamstime.com/b/default-avatar-photo-placeholder-profile-icon-eps-file-easy-to-edit-default-avatar-photo-placeholder-profile-icon-124557887.jpg"
                      alt="Avatar"
                    />
                    <div className="flex flex-col mx-2">
                      <a
                        href=""
                        className="font-semibold text-xs font-mabry text-gray-700 hover:underline"
                      >
                        Fajrian Aidil Pratama
                      </a>
                    </div>
                  </div>
                  <div className="flex w-1/3 justify-end text-xs font-mabry text-gray-600 ">
                    <span>9 minutes read</span>
                  </div>
                </div>
              </section>
            </div>
          </div>

          <div className="transition-all duration-150 flex w-full px-2 py-4 md:w-1/2 lg:w-1/3">
            <div className="relative flex flex-col border-2 border-gray-600 items-stretch min-h-full pb-4 mb-6 transition-all duration-150 bg-white rounded-lg shadow-lg hover:shadow-2xl">
              <div className="md:flex-shrink-0">
                <Image
                  src={fortnite}
                  className="object-fill w-full rounded-lg rounded-b-none"
                  alt=""
                />
              </div>

              <h1 className="px-4 pt-2 font-mabrybold font-bold">
                Lorem Ipsum dolor sit amet
              </h1>
              <div className="flex flex-row flex-wrap w-full h-40 px-4 py-2 overflow-hidden text-sm font-mabry leading-tight text-justify text-gray-700">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias,
                magni fugiat, odit incidunt necessitatibus aut nesciunt
                exercitationem aliquam id voluptatibus quisquam maiores officia
                sit amet accusantium aliquid quo obcaecati quasi.
              </div>
              <section className="absolute bottom-4 px-4 py-2 w-full ">
                <div className="flex w-full items-center justify-between space-x-2 ">
                  <div className="flex w-2/3 items-center justify-start ">
                    <img
                      className="object-cover h-8 rounded-full"
                      src="https://thumbs.dreamstime.com/b/default-avatar-photo-placeholder-profile-icon-eps-file-easy-to-edit-default-avatar-photo-placeholder-profile-icon-124557887.jpg"
                      alt="Avatar"
                    />
                    <div className="flex flex-col mx-2">
                      <a
                        href=""
                        className="font-semibold text-xs font-mabry text-gray-700 hover:underline"
                      >
                        Fajrian Aidil Pratama
                      </a>
                    </div>
                  </div>
                  <div className="flex w-1/3 justify-end text-xs font-mabry text-gray-600 ">
                    <span>9 minutes read</span>
                  </div>
                </div>
              </section>
            </div>
          </div>
        </section> */}

          <div className='flex flex-row mx-auto w-3/4 space-x-6 justify-center2 items-center2'>
            <Link href={''} className=''>
              <Image src={minecraft} alt="" className="object-cover h-36 w-96 rounded" />
            </Link>
            <div className='flex flex-col space-y-0.5 leading-tight'>
              <div className="flex space-x-2 items-center">
                <Link href={''} className="p-0.5 bg-[#ffff00]">
                  <span className="font-mabryblack text-xs text-slate-900">NEWS</span>
                </Link>
                <span className="font-mabrybold text-xs text-gray-700">April 16, 2023</span>
              </div>
              <Link href={''} className='text-[24px] font-mabryblack hover:text-pink-600'>
                Build that thing you’ve been imagining
              </Link>
              <span className='text-[14px] leading-relaxed font-mabry'>
                Millions of people use Glitch to express themselves, try new things, and help others learn. We’re fun and easy, so you spend less time setting up and more time exploring, experimenting, making mistakes and growing.
              </span>
            </div>
          </div>
          <div className='flex flex-row mx-auto w-3/4 space-x-6 justify-center2 items-center2'>
            <Link href={''} className=''>
              <Image src={minecraft} alt="" className="object-cover h-36 w-96 rounded" />
            </Link>
            <div className='flex flex-col space-y-0.5 leading-tight'>
              <div className="flex space-x-2 items-center">
                <Link href={''} className="p-0.5 bg-[#ffff00]">
                  <span className="font-mabryblack text-xs text-slate-900">NEWS</span>
                </Link>
                <span className="font-mabrybold text-xs text-gray-700">April 16, 2023</span>
              </div>
              <Link href={''} className='text-[24px] font-mabryblack hover:text-pink-600'>
                Build that thing you’ve been imagining
              </Link>
              <span className='text-[14px] leading-relaxed font-mabry'>
                Millions of people use Glitch to express themselves, try new things, and help others learn. We’re fun and easy, so you spend less time setting up and more time exploring, experimenting, making mistakes and growing.
              </span>
            </div>
          </div>
          <div className='flex flex-row mx-auto w-3/4 space-x-6 justify-center2 items-center2'>
            <Link href={''} className=''>
              <Image src={minecraft} alt="" className="object-cover h-36 w-96 rounded" />
            </Link>
            <div className='flex flex-col space-y-0.5 leading-tight'>
              <div className="flex space-x-2 items-center">
                <Link href={''} className="p-0.5 bg-[#ffff00]">
                  <span className="font-mabryblack text-xs text-slate-900">NEWS</span>
                </Link>
                <span className="font-mabrybold text-xs text-gray-700">April 16, 2023</span>
              </div>
              <Link href={''} className='text-[24px] font-mabryblack hover:text-pink-600'>
                Build that thing you’ve been imagining
              </Link>
              <span className='text-[14px] leading-relaxed font-mabry'>
                Millions of people use Glitch to express themselves, try new things, and help others learn. We’re fun and easy, so you spend less time setting up and more time exploring, experimenting, making mistakes and growing.
              </span>
            </div>
          </div>
          <div className='flex flex-row mx-auto w-3/4 space-x-6 justify-center2 items-center2'>
            <Link href={''} className=''>
              <Image src={minecraft} alt="" className="object-cover h-36 w-96 rounded" />
            </Link>
            <div className='flex flex-col space-y-0.5 leading-tight'>
              <div className="flex space-x-2 items-center">
                <Link href={''} className="p-0.5 bg-[#ffff00]">
                  <span className="font-mabryblack text-xs text-slate-900">NEWS</span>
                </Link>
                <span className="font-mabrybold text-xs text-gray-700">April 16, 2023</span>
              </div>
              <Link href={''} className='text-[24px] font-mabryblack hover:text-pink-600'>
                Build that thing you’ve been imagining
              </Link>
              <span className='text-[14px] leading-relaxed font-mabry'>
                Millions of people use Glitch to express themselves, try new things, and help others learn. We’re fun and easy, so you spend less time setting up and more time exploring, experimenting, making mistakes and growing.
              </span>
            </div>
          </div>
          <div className='flex flex-row mx-auto w-3/4 space-x-6 justify-center2 items-center2'>
            <Link href={''} className=''>
              <Image src={minecraft} alt="" className="object-cover h-36 w-96 rounded" />
            </Link>
            <div className='flex flex-col space-y-0.5 leading-tight'>
              <div className="flex space-x-2 items-center">
                <Link href={''} className="p-0.5 bg-[#ffff00]">
                  <span className="font-mabryblack text-xs text-slate-900">NEWS</span>
                </Link>
                <span className="font-mabrybold text-xs text-gray-700">April 16, 2023</span>
              </div>
              <Link href={''} className='text-[24px] font-mabryblack hover:text-pink-600'>
                Build that thing you’ve been imagining
              </Link>
              <span className='text-[14px] leading-relaxed font-mabry'>
                Millions of people use Glitch to express themselves, try new things, and help others learn. We’re fun and easy, so you spend less time setting up and more time exploring, experimenting, making mistakes and growing.
              </span>
            </div>
          </div>
          

          <div className="flex  mx-auto w-3/4 space-x-6">
          <div className="flex w-full pt-5">
                <Link href={""} className="relative w-full inline-block text-lg group">
                  <span className="relative flex z-10  x-3 py-3 justify-center overflow-hidden leading-tight text-sm font-mabrybold text-gray-800 transition-colors duration-300 ease-out border-2 border-gray-800 rounded ">
                    <span className="absolute inset-0 w-full h-full px-5 py-3 rounded bg-yellow-200 group-hover:bg-yellow-300"></span>
                    {/* <span className="absolute left-0 w-22 h-22 -ml-2 transition-all duration-300 origin-top-right -rotate-90 -translate-x-full translate-y-12 bg-gray-900 group-hover:-rotate-180 ease"></span> */}
                    <span className="relative font-mabryblack">Load More</span>
                  </span>
                  <span
                    className="absolute bottom-0 right-0 w-full h-11 -mb-1 -mr-1 transition-all duration-200 ease-linear bg-gray-900 rounded group-hover:mb-00 group-hover:mr-00"
                    data-rounded="rounded-lg"
                  ></span>
                </Link>
              </div>
          </div>
      </div>
      <Footer />
    </>
  );
}
