import React, { useEffect } from "react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import Notice from '@/components/Notice'
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import tournament from "@/img/tournament.jpg"
import festival from "@/img/festival.png"
import festival1 from "@/img/festival1.png"



export default function Schedule() {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <Notice />

        <div className="h-max flex py-12 pb-20 px-20 bg-[#f2f2f2]">
          <div className="flex flex-col w-full mx-auto space-y-6 justify-center2 items-center">
            <div className="flex flex-col space-y-2">
                <span className="text-3xl font-mabryblack">Schedule Tournament</span>
                <span className="text-lg font-mabrybold leading-tight">See it all and immerse yourself in emotion – from the glee to the grit to the glory – at the 70th Sydney Film Festival this 7–18 June 2023.</span>
            </div>

            <div className="py-2 w-full border-b-2">
                <span className="font-mabryitalic text-lg">17 juli 2023</span>
            </div>
            <div className="w-full pt-1 grid md:grid-cols-2 gap-8">
                <div className="w-[380px] flex flex-row ">
                    <div className=" flex flex-col space-y-1 px-4 py-3 leading-tight bg-black text-yellow-500">
                        <span className="font-mabryblack text-lg">Dota2 Tournament</span>
                        <span className="font-mabry leading-tight text-sm">Special offers from our restaurant partners</span>
                    </div>
                    <div className="">
                        <Image src={tournament} className="object-cover h-48 w-60"/>
                    </div>
                </div>
                <div className="w-[380px] flex flex-row ">
                    <div className=" flex flex-col space-y-1 px-4 py-3 leading-tight bg-[#fd9c0c] ">
                        <span className="font-mabryblack text-lg">Dota2 Tournament</span>
                        <span className="font-mabry leading-tight text-sm">Special offers from our restaurant partners</span>
                    </div>
                    <div className="">
                        <Image src={festival} className="object-cover h-48 w-60"/>
                    </div>
                </div>
                <div className="w-[380px] flex flex-row ">
                    <div className=" flex flex-col space-y-1 px-4 py-3 leading-tight bg-black text-yellow-500">
                        <span className="font-mabryblack text-lg">Dota2 Tournament</span>
                        <span className="font-mabry leading-tight text-sm">Special offers from our restaurant partners</span>
                    </div>
                    <div className="">
                        <Image src={tournament} className="object-cover h-48 w-60"/>
                    </div>
                </div>
                <div className="w-[380px] flex flex-row ">
                    <div className=" flex flex-col space-y-1 px-4 py-3 leading-tight bg-[#fd9c0c] ">
                        <span className="font-mabryblack text-lg">Dota2 Tournament</span>
                        <span className="font-mabry leading-tight text-sm">Special offers from our restaurant partners</span>
                    </div>
                    <div className="">
                        <Image src={festival} className="object-cover h-48 w-60"/>
                    </div>
                </div>
            </div>
          </div>
        </div>
        <Footer />
      </>
    );
}