import React, { useEffect, useState, useRef } from "react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Report from "@/components/Report";
import Rate from "@/components/Rate";
import ReviewLine from "@/components/ReviewLine";

import lastofus from "@/img/lastofus.jpg";
import lastofus1 from "@/img/lastofus1.jpg";
import lastofus2 from "@/img/lastofus2.jpg";
import lastofus3 from "@/img/lastofus3.jpg";
import lastofus4 from "@/img/lastofus4.jpg";
import lastofus5 from "@/img/lastofus5.jpg";
import lastofus6 from "@/img/lastofus6.jpg";
import pravatar from "@/img/300.jpg";

import arrowLeft from "@/img/icon_arrow-left.png";
import arrowRight from "@/img/icon_arrow-right.png";
import GoTop from "@/components/GoTop";
import Tags from "@/components/Tags";
import Author from "@/components/Author";
import ImageReview from "@/components/ImageReview";
import Breadcrumb from "@/components/Breadcrumb";

export default function Review() {
  const [reportModalOpen, setReportModalOpen] = useState(false);
  const [rateModalOpen, setRateModalOpen] = useState(false);
  //   useEffect(() => {
  //     window.scrollTo(0, 0);
  //   }, []);

  let scrl = useRef(null);
  const shiftN = 230;
  const [scrollX, setscrollX] = useState(0);
  const [scrolEnd, setscrolEnd] = useState(false);

  const slide = (shift) => {
    scrl.current.scrollLeft += shift;
    setscrollX(scrollX + shift);

    if (
      Math.floor(scrl.current.scrollWidth - scrl.current.scrollLeft) <=
      scrl.current.offsetWidth
    ) {
      setscrolEnd(true);
    } else {
      setscrolEnd(false);
    }
  };

  const scrollCheck = () => {
    setscrollX(scrl.current.scrollLeft);
    if (
      Math.floor(scrl.current.scrollWidth - scrl.current.scrollLeft) <=
      scrl.current.offsetWidth
    ) {
      setscrolEnd(true);
    } else {
      setscrolEnd(false);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <GoTop />

      <div className="flex mx-auto w-full pt-16 pb-2 px-4 bg-[#f6f8f7]">
        <div className="flex justify-center items-center w-full bg-green-100 h-20">
          <div className="text-gray-500">advertising</div>
        </div>
      </div>
      <div className="bg-[#f6f8f7]">
        <div className="container w-full bg-[#f6f8f7] md:max-w-3xl mx-auto flex flex-col  items-center px-4 md:px-4">
          <div className="flex flex-col py-2 md:py-4">
            <Breadcrumb />
            <span className="font-mabryblack uppercase leading-tight md:leading-11 text-2xl md:text-5xl pb-2 text-gray-900">
              Dead Space remake review: A masterclass in survival horror, all
              over again
            </span>
            <div className="flex flex-col md:flex-row space-y-1 md:justify-between border-t-2 border-[#d54215] pt-2 md:pt-2">
              <span>
                <p className="text-sm md:text-sm font-mabry text-gray-900">
                  Published 19 February 2019
                </p>
              </span>
              <div className="font-mabry">
                <div className=" flex justify-between items-center text-base md:text-sm text-green-500 font-bold">
                  <div className="flex justify-end space-x-2">
                    <button>
                      <div className="flex rounded border py-1.5 px-2 shadow-menu border-gray-800 bg-[#1877f2] hover:bg-[#1877f2]  fill-[#1877f2] hover:fill-white  items-center justify-between md:space-x-1 hover:shadow-blue-500/50 ">
                        <span className="hidden md:block text-white font-mabrybold">
                          Facebook
                        </span>
                        <svg
                          className="w-5 h-5 md:w-4 md:h-4 text-white"
                          fill="currentColor"
                          viewBox="0 0 24 24"
                          aria-hidden="true"
                        >
                          <path
                            fillRule="evenodd"
                            d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z"
                            clipRule="evenodd"
                          ></path>
                        </svg>
                      </div>
                    </button>
                    <button>
                      <div className="flex rounded border py-1.5 px-2 shadow-menu border-gray-800 bg-[#1d9bf0] hover:bg-[#1d9bf0] fill-[#1d9bf0] hover:fill-white  items-center justify-between md:space-x-1 hover:shadow-sky-500/50">
                        <span className="hidden md:block text-white font-mabrybold">
                          Twitter
                        </span>
                        <svg
                          className="w-5 h-5 md:w-4 md:h-4 text-white"
                          fill="currentColor"
                          viewBox="0 0 24 24"
                          aria-hidden="true"
                        >
                          <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84"></path>
                        </svg>
                      </div>
                    </button>
                    <button>
                      <div className="flex rounded border py-1.5 px-2 shadow-menu border-gray-800 bg-gray-800 hover:bg-black  hover:fill-white  items-center justify-between md:space-x-1 hover:shadow-sky-500/50">
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          strokeWidth={1.5}
                          stroke="currentColor"
                          className="w-5 h-5 md:w-4 md:h-4 text-white"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            d="M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244"
                          />
                        </svg>

                        <span className="hidden md:block text-white font-mabry">
                          Copy url
                        </span>
                      </div>
                    </button>
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        setReportModalOpen(true);
                      }}
                    >
                      <div className="flex rounded border py-1.5 px-2 shadow-menu border-gray-800 bg-white hover:bg-white text-black hover:fill-white  items-center justify-between space-x-1 hover:shadow-sky-500/50">
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          viewBox="0 0 24 24"
                          fill="currentColor"
                          className="w-5 h-5 md:w-4 md:h-4"
                        >
                          <path
                            fillRule="evenodd"
                            d="M3 2.25a.75.75 0 01.75.75v.54l1.838-.46a9.75 9.75 0 016.725.738l.108.054a8.25 8.25 0 005.58.652l3.109-.732a.75.75 0 01.917.81 47.784 47.784 0 00.005 10.337.75.75 0 01-.574.812l-3.114.733a9.75 9.75 0 01-6.594-.77l-.108-.054a8.25 8.25 0 00-5.69-.625l-2.202.55V21a.75.75 0 01-1.5 0V3A.75.75 0 013 2.25z"
                            clipRule="evenodd"
                          />
                        </svg>

                        <span className="hidden md:block text-black font-mabry">
                          Report
                        </span>
                      </div>
                    </button>
                    <Report
                      modalOpen={reportModalOpen}
                      setModalOpen={setReportModalOpen}
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="w-full md:w-full z-10">
            <Image src={lastofus} quality={100} alt="" />
          </div>
        </div>
        <div className="container w-full bg-[#f6f8f7] md:max-w-3xl mx-auto flex flex-col md:flex-row items-center mt-4 px-4 md:px-4">
          <div className="flex flex-row mx-auto w-full justify-center2 items-center">
            <div className="flex flex-col md:flex-row w-full md:justify-between space-y-3 md:space-x-3">
              
              <div className="flex flex-col w-full md:w-2/3 px-3 py-2 md:px-3 md:py-2 rounded border-2 border-gray-800 bg-[#114388] shadow-menu">
                <div className="text-lg font-mabrybold uppercase text-white">
                  The last of us part I
                </div>
                <div className="text-xs font-mabry text-white">
                  Release Date: Sep 2, 2022
                </div>
              </div>

              <div className="flex md:justify-end text-white uppercase px-3 py-2 md:px-3 md:py-2 rounded border-2 border-gray-800 bg-[#f25c34] shadow-menu">
                <div className="flex flex-wrap justify-end text-xs font-mabrybold cursor-pointer">
                  <span className="m-0.5 hover:underline underline-offset-2">
                    PlayStation 5
                  </span>
                  <span className="m-0.5 hover:underline underline-offset-2">
                    Nintendo
                  </span>
                  <span className="m-0.5 hover:underline underline-offset-2">
                    PC / MAC
                  </span>
                  <span className="m-0.5 hover:underline underline-offset-2">
                    Xbox
                  </span>
                  <span className="m-0.5 hover:underline underline-offset-2">
                    Console
                  </span>
                  <span className="m-0.5 hover:underline underline-offset-2">
                    Google
                  </span>
                  <span className="m-0.5 hover:underline underline-offset-2">
                    Smartphone
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="bg-[#f6f8f7]">
        <div className="container w-full md:max-w-3xl mx-auto pt-4 md:pt-4 px-4 md:px-0">
          <div className="w-full px-4 md:px-6 text-lg text-gray-800 leading-normal">
            <div className="flex w-full space-x-3">
              <div className="w-full">
               
                <div className="flex flex-col md:flex-row w-full px-0 py-4 space-y-3 md:space-x-4">

                  <div className="w-full md:w-1/2 flex justify-center border border-gray-800 rounded shadow-stack-sm  bg-white">
                    <div className="flex flex-col w-full text-gray-900">
                      <div className="border-b border-gray-800 py-3 px-3 leading-tight">
                        <span className="text-sm font-mabrybold text-gray-900">
                          The Last of us
                        </span>
                      </div>
                      <div className="flex justify-between items-center border-b border-gray-800 py-3 px-3">
                        <div className="text-sm font-mabrybold">Rating</div>
                        <div className="text-sm font-mabry">M</div>
                      </div>
                      <div className="flex justify-between items-center border-b border-gray-800 py-3 px-3">
                        <div className="text-sm font-mabrybold">Developer</div>
                        <div className="text-sm font-mabry">
                          CD Projekt Red Studio
                        </div>
                      </div>
                      <div className="flex justify-between items-center border-b border-gray-800 py-3 px-3">
                        <div className="text-sm font-mabrybold">Genre</div>
                        <div className="text-sm font-mabry">
                          Role-Playing, Action RPG
                        </div>
                      </div>
                      <div className="flex justify-between items-center  border-gray-800 py-3 px-3">
                        <div className="text-sm font-mabrybold">
                          Multiplayer
                        </div>
                        <div className="text-sm font-mabry">No</div>
                      </div>
                    </div>
                  </div>
                  <div className="w-full md:w-1/2 flex space-x-3">
                    <div className="flex  h-12 w-12 items-center justify-center border shadow-menu border-gray-800 bg-green-300 rounded-full px-2 py-2">
                      <span className="text-lg font-mabrybold text-gray-900">
                        8.7
                      </span>
                    </div>
                    <div className="flex w-2/3 flex-col leading-tight">
                      <div className="text-sm font-mabrybold text-gray-900">
                        User Score
                      </div>
                      <div className="text-xs font-mabry leading-snug text-gray-900">
                        Generally favorable reviews based on 201 Ratings{" "}
                      </div>
                      <div
                        className="flex w-16 shadow-menu bg-orange-600 border border-gray-800 px-1 text-xs text-white rounded cursor-pointer"
                        onClick={(e) => {
                          e.stopPropagation();
                          setRateModalOpen(true);
                        }}
                      >
                        Rate now
                      </div>
                      <Rate
                        modalOpen={rateModalOpen}
                        setModalOpen={setRateModalOpen}
                      />
                    </div>
                  </div>
                </div>

                {/* CONTENT */}
                <div className=" text-md font-mabry leading-snug">
                  <p className="py-3">
                    One of the most influential horror games of all time returns
                    to show us all how it's done. 15 years later, Dead Space
                    asserts its place at the top.
                  </p>

                  <p className="py-3">
                    As you hop aboard the USG Ishimura and into the suit of Dead
                    Space protagonist, Isaac Clarke, you’ll unearth terror like
                    never before in the form of Necromorphs. These alien
                    horrors, alongside undertones of religious fanaticism, make
                    the USG Ishimura one of the most terrifying settings in the
                    survival horror genre.
                  </p>
                  <p className="py-3">
                    In the same vein as Alien: Isolation, there is something so
                    claustrophobic about being marooned in outer space; the
                    immediate threat of body-horror aliens, the religious
                    fanatics encouraging them to feed, and this huge vessel with
                    a myriad of broken… everything. It gets in your head. Dead
                    Space is a test of Isaac’s patience and resilience, and as
                    you reach the third act of the game, you can tell that he’s
                    wearing thin.
                  </p>
                  <p className="py-3">
                    There are no safe spaces, and there is no escape from the
                    USG Ishimura. Even in rooms with Save Stations and Stores,
                    you can’t be sure that a Lurker or Slasher won't appear.
                    This feeling of insecurity is paired with a satisfying
                    combat system that Dead Space wouldn't feel the same
                    without. Your headshots don't matter aboard the USG
                    Ishimura. It's all about dismemberment. With abilities such
                    as Stasis and Kinesis letting you slow enemies down and
                    impale them with common items, combat is overwhelming at
                    first. The second that you get into the swing of things,
                    however, you can become incredibly creative when slaying
                    hordes of Necromorphs.
                  </p>
                  <p className="py-3">
                    Thanks to Dead Space’s 'Intensity Director', the spawn of
                    hostile enemies and the way lighting or audio functions can
                    be entirely unique to your personal experience of the game,
                    so fights won't play out the same. You know what this means?
                    You truly never know what to expect. This, accompanied by a
                    terrifying score, ensures that Dead Space will get under
                    your skin as much as it does Isaac's.
                  </p>
                  <p className="py-3">
                    Dead Space’s music and orchestral scoring reaches haunting
                    peaks that echo the work of John Carpenter (why is he not
                    directing the Dead Space film again?), but not just when
                    you’re in danger; the score will creep up on you and terrify
                    you even during moments of safety. At no point does Dead
                    Space choose to slow down; it constantly keeps you on the
                    edge of your seat and has you questioning everything with
                    various crescendos and racing tempos. What was that
                    apparition? Why is Nicole talking about Isaac 'making
                    everyone whole again'? What’s actually going on here?
                  </p>
                  <p className="py-3">
                    Dead Space has a plot that is genuinely interesting, and
                    when it comes to piling on the tension, it doesn’t rely on
                    cheap scares, either. If anything, the game serves as a
                    master class in creating tension and suspense effectively in
                    horror games – even now, some 15 years after the original
                    launched. Take entering an elevator, for example. You’re
                    thinking that you’re safe now, and that the Necromorph
                    pursuing you definitely can’t fit in here. Suddenly, it’s
                    bursting through the door, and you’ve spat out your drink
                    that you thought you were finally safe to have a sip of. Or,
                    you’re walking down a long corridor when the turbine at the
                    end suddenly breaks. You immediately aim your gun and
                    prepare for trouble, but in this instance, it was a false
                    alarm; now you’re on edge all over again for no reason.
                  </p>
                </div>

                {/*  */}
                <ImageReview />
                {/*  */}

                {/* SOURCE */}
                <div className="md:text-sm text-gray-500 px-2 md:px-0 py-3 font-mabry">
                  Source:{" "}
                  <a
                    href="https://mydramalist.com/article/an-ultra-fan-guide-to-lee-elijah"
                    className="italic underline font-mabryitalic"
                  >
                    https://mydramalist.com/article/an-ultra-fan-guide-to-lee-elijah
                  </a>
                </div>

                {/* TAGS */}
                <Tags />

                {/* <hr className="border-b-2 border-gray-400 mb-8 mx-4" /> */}

                <Author />

                <ReviewLine />
                {/* <DetailComment /> */}
                {/* <hr className="border-b-2 border-gray-400 mb-8 mx-4" /> */}
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}
