import React from "react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Filter from "@/components/Filter";

import ant from "@/img/products/ant.jpg";
import apes from "@/img/products/apes.jpg";
import basket from "@/img/products/basket.jpg";
import batman from "@/img/products/batman.jpg";
import bumble from "@/img/products/bumble.jpg";
import blackpanther from "@/img/products/blackpanther.jpg";
import captain from "@/img/products/captain.jpg";
import cpo from "@/img/products/cpo.jpg";
import hulk from "@/img/products/hulk.jpg";
import decepticon from "@/img/products/decepticon.jpg";
import kyubi from "@/img/products/kyubi.jpg";
import mma from "@/img/products/mma.jpg";
import naruto from "@/img/products/naruto.jpg";
import neca from "@/img/products/neca.jpg";
import obsolete from "@/img/products/obsolete.jpg";
import predator from "@/img/products/predator.jpg";
import psyduck from "@/img/products/psyduck.jpg";
import rim from "@/img/products/rim.jpg";
import ripley from "@/img/products/ripley.jpeg";
import robot from "@/img/products/robot.jpg";
import shohoku from "@/img/products/shohoku.jpg";
import spiderman from "@/img/products/spiderman.jpg";
import transformer from "@/img/products/transformer.jpg";
import wolferine from "@/img/products/wolferine.jpg";
import ironman from "@/img/products/ironman.jpg";
import inuyasa from "@/img/products/inuyasa.jpg";
import warhammer from "@/img/products/warhammer.jpg";
import venom from "@/img/products/venom.jpg";

export default function Products() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div className="h-max flex py-20 flex-col space-y-10 px-10 justify-center2 items-center2 bg-yellow-400">
        <div className="flex flex-row mx-auto  space-x-6 justify-center2 items-center">
          <span className="text-3xl font-mabrybold">Deals</span>
        </div>
      </div>

      <Filter />

      <div className="h-max flex flex-col px-8 justify-center2 items-center2 bg-[#f6f8f7]">
        <div className="flex flex-row mx-auto w-full space-x-6 justify-center2 items-center">
          <section className="flex flex-row flex-wrap mx-auto justify-center2 items-center3">
            {/*  */}
            <Link href={"/products/antman"} className=" transition-all duration-150 flex w-full px-2 py-4 md:w-1/3 lg:w-1/3  cursor-pointer">
              <div className=" flex flex-col border border-gray-600 items-stretch min-h-full  transition-all duration-150 bg-white rounded-md shadow hover:shadow">
                <div className="relative md:flex-shrink-0 border-b">
                  <Image
                    src={ant}
                    className="object-fill w-full rounded-md rounded-b-none "
                    alt=""
                  />
                </div>
                <div className="px-3 py-2  h-16 font-mabry">
                  <span>
                    Lorem Ipsum dolor sit amet
                  </span>
                </div>
                <div className="flex w-full mt-2 px-3 h-14 border-t border-gray-600 ">
                  <div className="w-3/5 flex items-center">
                    <span className="text-sm font-mabrybold">Rp 1.400.000</span>
                  </div>
                  <div className="flex w-2/5 border-l border-gray-600 space-x-1 justify-center items-center">
                    <div className="flex items-center justify-center space-x-1">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 24 24"
                        fill="currentColor"
                        className="w-4 h-4"
                      >
                        <path
                          fillRule="evenodd"
                          d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z"
                          clipRule="evenodd"
                        />
                      </svg>
                      <span className="text-xs font-mabry">5.0</span>
                    </div>
                    <span className="text-xs font-mabry">(224)</span>
                  </div>
                </div>
              </div>
            </Link> 
            {/*  */}
            <Link href={"/products/antman"} className=" transition-all duration-150 flex w-full px-2 py-4 md:w-1/3 lg:w-1/3  cursor-pointer">
              <div className=" flex flex-col border border-gray-600 items-stretch min-h-full  transition-all duration-150 bg-white rounded-md shadow hover:shadow">
                <div className="relative md:flex-shrink-0 border-b">
                  <Image
                    src={apes}
                    className="object-fill w-full rounded-md rounded-b-none "
                    alt=""
                  />
                </div>
                <div className="px-3 py-2  h-16 font-mabry">
                  <span>
                    Lorem Ipsum dolor sit amet
                  </span>
                </div>
                <div className="flex w-full mt-2 px-3 h-14 border-t border-gray-600 ">
                  <div className="w-3/5 flex items-center">
                    <span className="text-sm font-mabrybold">Rp 1.400.000</span>
                  </div>
                  <div className="flex w-2/5 border-l border-gray-600 space-x-1 justify-center items-center">
                    <div className="flex items-center justify-center space-x-1">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 24 24"
                        fill="currentColor"
                        className="w-4 h-4"
                      >
                        <path
                          fillRule="evenodd"
                          d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z"
                          clipRule="evenodd"
                        />
                      </svg>
                      <span className="text-xs font-mabry">5.0</span>
                    </div>
                    <span className="text-xs font-mabry">(224)</span>
                  </div>
                </div>
              </div>
            </Link>
            {/*  */}
            <Link href={"/products/antman"} className=" transition-all duration-150 flex w-full px-2 py-4 md:w-1/3 lg:w-1/3  cursor-pointer">
              <div className=" flex flex-col border border-gray-600 items-stretch min-h-full  transition-all duration-150 bg-white rounded-md shadow hover:shadow">
                <div className="relative md:flex-shrink-0 border-b">
                  <Image
                    src={basket}
                    className="object-fill w-full rounded-md rounded-b-none "
                    alt=""
                  />
                </div>
                <div className="px-3 py-2  h-16 font-mabry">
                  <span>
                    Lorem Ipsum dolor sit amet
                  </span>
                </div>
                <div className="flex w-full mt-2 px-3 h-14 border-t border-gray-600 ">
                  <div className="w-3/5 flex items-center">
                    <span className="text-sm font-mabrybold">Rp 1.400.000</span>
                  </div>
                  <div className="flex w-2/5 border-l border-gray-600 space-x-1 justify-center items-center">
                    <div className="flex items-center justify-center space-x-1">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 24 24"
                        fill="currentColor"
                        className="w-4 h-4"
                      >
                        <path
                          fillRule="evenodd"
                          d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z"
                          clipRule="evenodd"
                        />
                      </svg>
                      <span className="text-xs font-mabry">5.0</span>
                    </div>
                    <span className="text-xs font-mabry">(224)</span>
                  </div>
                </div>
              </div>
            </Link>
            {/*  */}
            <Link href={"/products/antman"} className=" transition-all duration-150 flex w-full px-2 py-4 md:w-1/3 lg:w-1/3  cursor-pointer">
              <div className=" flex flex-col border border-gray-600 items-stretch min-h-full  transition-all duration-150 bg-white rounded-md shadow hover:shadow">
                <div className="relative md:flex-shrink-0 border-b">
                  <Image
                    src={batman}
                    className="object-fill w-full rounded-md rounded-b-none "
                    alt=""
                  />
                </div>
                <div className="px-3 py-2  h-16 font-mabry">
                  <span>
                    Lorem Ipsum dolor sit amet
                  </span>
                </div>
                <div className="flex w-full mt-2 px-3 h-14 border-t border-gray-600 ">
                  <div className="w-3/5 flex items-center">
                    <span className="text-sm font-mabrybold">Rp 1.400.000</span>
                  </div>
                  <div className="flex w-2/5 border-l border-gray-600 space-x-1 justify-center items-center">
                    <div className="flex items-center justify-center space-x-1">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 24 24"
                        fill="currentColor"
                        className="w-4 h-4"
                      >
                        <path
                          fillRule="evenodd"
                          d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z"
                          clipRule="evenodd"
                        />
                      </svg>
                      <span className="text-xs font-mabry">5.0</span>
                    </div>
                    <span className="text-xs font-mabry">(224)</span>
                  </div>
                </div>
              </div>
            </Link>
            {/*  */}
            <Link href={"/products/antman"} className=" transition-all duration-150 flex w-full px-2 py-4 md:w-1/3 lg:w-1/3  cursor-pointer">
              <div className=" flex flex-col border border-gray-600 items-stretch min-h-full  transition-all duration-150 bg-white rounded-md shadow hover:shadow">
                <div className="relative md:flex-shrink-0 border-b">
                  <Image
                    src={blackpanther}
                    className="object-fill w-full rounded-md rounded-b-none "
                    alt=""
                  />
                </div>
                <div className="px-3 py-2  h-16 font-mabry">
                  <span>
                    Lorem Ipsum dolor sit amet
                  </span>
                </div>
                <div className="flex w-full mt-2 px-3 h-14 border-t border-gray-600 ">
                  <div className="w-3/5 flex items-center">
                    <span className="text-sm font-mabrybold">Rp 1.400.000</span>
                  </div>
                  <div className="flex w-2/5 border-l border-gray-600 space-x-1 justify-center items-center">
                    <div className="flex items-center justify-center space-x-1">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 24 24"
                        fill="currentColor"
                        className="w-4 h-4"
                      >
                        <path
                          fillRule="evenodd"
                          d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z"
                          clipRule="evenodd"
                        />
                      </svg>
                      <span className="text-xs font-mabry">5.0</span>
                    </div>
                    <span className="text-xs font-mabry">(224)</span>
                  </div>
                </div>
              </div>
            </Link>
            {/*  */}
            <Link href={"/products/antman"} className=" transition-all duration-150 flex w-full px-2 py-4 md:w-1/3 lg:w-1/3  cursor-pointer">
              <div className=" flex flex-col border border-gray-600 items-stretch min-h-full  transition-all duration-150 bg-white rounded-md shadow hover:shadow">
                <div className="relative md:flex-shrink-0 border-b">
                  <Image
                    src={captain}
                    className="object-fill w-full rounded-md rounded-b-none "
                    alt=""
                  />
                </div>
                <div className="px-3 py-2  h-16 font-mabry">
                  <span>
                    Lorem Ipsum dolor sit amet
                  </span>
                </div>
                <div className="flex w-full mt-2 px-3 h-14 border-t border-gray-600 ">
                  <div className="w-3/5 flex items-center">
                    <span className="text-sm font-mabrybold">Rp 1.400.000</span>
                  </div>
                  <div className="flex w-2/5 border-l border-gray-600 space-x-1 justify-center items-center">
                    <div className="flex items-center justify-center space-x-1">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 24 24"
                        fill="currentColor"
                        className="w-4 h-4"
                      >
                        <path
                          fillRule="evenodd"
                          d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z"
                          clipRule="evenodd"
                        />
                      </svg>
                      <span className="text-xs font-mabry">5.0</span>
                    </div>
                    <span className="text-xs font-mabry">(224)</span>
                  </div>
                </div>
              </div>
            </Link>
            {/*  */}
            <Link href={"/products/antman"} className=" transition-all duration-150 flex w-full px-2 py-4 md:w-1/3 lg:w-1/3  cursor-pointer">
              <div className=" flex flex-col border border-gray-600 items-stretch min-h-full  transition-all duration-150 bg-white rounded-md shadow hover:shadow">
                <div className="relative md:flex-shrink-0 border-b">
                  <Image
                    src={ironman}
                    className="object-fill w-full rounded-md rounded-b-none "
                    alt=""
                  />
                </div>
                <div className="px-3 py-2  h-16 font-mabry">
                  <span>
                    Lorem Ipsum dolor sit amet
                  </span>
                </div>
                <div className="flex w-full mt-2 px-3 h-14 border-t border-gray-600 ">
                  <div className="w-3/5 flex items-center">
                    <span className="text-sm font-mabrybold">Rp 1.400.000</span>
                  </div>
                  <div className="flex w-2/5 border-l border-gray-600 space-x-1 justify-center items-center">
                    <div className="flex items-center justify-center space-x-1">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 24 24"
                        fill="currentColor"
                        className="w-4 h-4"
                      >
                        <path
                          fillRule="evenodd"
                          d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z"
                          clipRule="evenodd"
                        />
                      </svg>
                      <span className="text-xs font-mabry">5.0</span>
                    </div>
                    <span className="text-xs font-mabry">(224)</span>
                  </div>
                </div>
              </div>
            </Link>
            {/*  */}
            <Link href={"/products/antman"} className=" transition-all duration-150 flex w-full px-2 py-4 md:w-1/3 lg:w-1/3  cursor-pointer">
              <div className=" flex flex-col border border-gray-600 items-stretch min-h-full  transition-all duration-150 bg-white rounded-md shadow hover:shadow">
                <div className="relative md:flex-shrink-0 border-b">
                  <Image
                    src={kyubi}
                    className="object-fill w-full rounded-md rounded-b-none "
                    alt=""
                  />
                </div>
                <div className="px-3 py-2  h-16 font-mabry">
                  <span>
                    Lorem Ipsum dolor sit amet
                  </span>
                </div>
                <div className="flex w-full mt-2 px-3 h-14 border-t border-gray-600 ">
                  <div className="w-3/5 flex items-center">
                    <span className="text-sm font-mabrybold">Rp 1.400.000</span>
                  </div>
                  <div className="flex w-2/5 border-l border-gray-600 space-x-1 justify-center items-center">
                    <div className="flex items-center justify-center space-x-1">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 24 24"
                        fill="currentColor"
                        className="w-4 h-4"
                      >
                        <path
                          fillRule="evenodd"
                          d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z"
                          clipRule="evenodd"
                        />
                      </svg>
                      <span className="text-xs font-mabry">5.0</span>
                    </div>
                    <span className="text-xs font-mabry">(224)</span>
                  </div>
                </div>
              </div>
            </Link>
            {/*  */}
            <Link href={"/products/antman"} className=" transition-all duration-150 flex w-full px-2 py-4 md:w-1/3 lg:w-1/3  cursor-pointer">
              <div className=" flex flex-col border border-gray-600 items-stretch min-h-full  transition-all duration-150 bg-white rounded-md shadow hover:shadow">
                <div className="relative md:flex-shrink-0 border-b">
                  <Image
                    src={naruto}
                    className="object-fill w-full rounded-md rounded-b-none "
                    alt=""
                  />
                </div>
                <div className="px-3 py-2  h-16 font-mabry">
                  <span>
                    Lorem Ipsum dolor sit amet
                  </span>
                </div>
                <div className="flex w-full mt-2 px-3 h-14 border-t border-gray-600 ">
                  <div className="w-3/5 flex items-center">
                    <span className="text-sm font-mabrybold">Rp 1.400.000</span>
                  </div>
                  <div className="flex w-2/5 border-l border-gray-600 space-x-1 justify-center items-center">
                    <div className="flex items-center justify-center space-x-1">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 24 24"
                        fill="currentColor"
                        className="w-4 h-4"
                      >
                        <path
                          fillRule="evenodd"
                          d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z"
                          clipRule="evenodd"
                        />
                      </svg>
                      <span className="text-xs font-mabry">5.0</span>
                    </div>
                    <span className="text-xs font-mabry">(224)</span>
                  </div>
                </div>
              </div>
            </Link>
            {/*  */}
            <Link href={"/products/antman"} className=" transition-all duration-150 flex w-full px-2 py-4 md:w-1/3 lg:w-1/3  cursor-pointer">
              <div className=" flex flex-col border border-gray-600 items-stretch min-h-full  transition-all duration-150 bg-white rounded-md shadow hover:shadow">
                <div className="relative md:flex-shrink-0 border-b">
                  <Image
                    src={shohoku}
                    className="object-fill w-full rounded-md rounded-b-none "
                    alt=""
                  />
                </div>
                <div className="px-3 py-2  h-16 font-mabry">
                  <span>
                    Lorem Ipsum dolor sit amet
                  </span>
                </div>
                <div className="flex w-full mt-2 px-3 h-14 border-t border-gray-600 ">
                  <div className="w-3/5 flex items-center">
                    <span className="text-sm font-mabrybold">Rp 1.400.000</span>
                  </div>
                  <div className="flex w-2/5 border-l border-gray-600 space-x-1 justify-center items-center">
                    <div className="flex items-center justify-center space-x-1">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 24 24"
                        fill="currentColor"
                        className="w-4 h-4"
                      >
                        <path
                          fillRule="evenodd"
                          d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z"
                          clipRule="evenodd"
                        />
                      </svg>
                      <span className="text-xs font-mabry">5.0</span>
                    </div>
                    <span className="text-xs font-mabry">(224)</span>
                  </div>
                </div>
              </div>
            </Link>
            {/*  */}
            <Link href={"/products/antman"} className=" transition-all duration-150 flex w-full px-2 py-4 md:w-1/3 lg:w-1/3  cursor-pointer">
              <div className=" flex flex-col border border-gray-600 items-stretch min-h-full  transition-all duration-150 bg-white rounded-md shadow hover:shadow">
                <div className="relative md:flex-shrink-0 border-b">
                  <Image
                    src={spiderman}
                    className="object-fill w-full rounded-md rounded-b-none "
                    alt=""
                  />
                </div>
                <div className="px-3 py-2  h-16 font-mabry">
                  <span>
                    Lorem Ipsum dolor sit amet
                  </span>
                </div>
                <div className="flex w-full mt-2 px-3 h-14 border-t border-gray-600 ">
                  <div className="w-3/5 flex items-center">
                    <span className="text-sm font-mabrybold">Rp 1.400.000</span>
                  </div>
                  <div className="flex w-2/5 border-l border-gray-600 space-x-1 justify-center items-center">
                    <div className="flex items-center justify-center space-x-1">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 24 24"
                        fill="currentColor"
                        className="w-4 h-4"
                      >
                        <path
                          fillRule="evenodd"
                          d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z"
                          clipRule="evenodd"
                        />
                      </svg>
                      <span className="text-xs font-mabry">5.0</span>
                    </div>
                    <span className="text-xs font-mabry">(224)</span>
                  </div>
                </div>
              </div>
            </Link>
            {/*  */}
            <Link href={"/products/antman"} className=" transition-all duration-150 flex w-full px-2 py-4 md:w-1/3 lg:w-1/3  cursor-pointer">
              <div className=" flex flex-col border border-gray-600 items-stretch min-h-full  transition-all duration-150 bg-white rounded-md shadow hover:shadow">
                <div className="relative md:flex-shrink-0 border-b">
                  <Image
                    src={wolferine}
                    className="object-fill w-full rounded-md rounded-b-none "
                    alt=""
                  />
                </div>
                <div className="px-3 py-2  h-16 font-mabry">
                  <span>
                    Lorem Ipsum dolor sit amet
                  </span>
                </div>
                <div className="flex w-full mt-2 px-3 h-14 border-t border-gray-600 ">
                  <div className="w-3/5 flex items-center">
                    <span className="text-sm font-mabrybold">Rp 1.400.000</span>
                  </div>
                  <div className="flex w-2/5 border-l border-gray-600 space-x-1 justify-center items-center">
                    <div className="flex items-center justify-center space-x-1">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 24 24"
                        fill="currentColor"
                        className="w-4 h-4"
                      >
                        <path
                          fillRule="evenodd"
                          d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z"
                          clipRule="evenodd"
                        />
                      </svg>
                      <span className="text-xs font-mabry">5.0</span>
                    </div>
                    <span className="text-xs font-mabry">(224)</span>
                  </div>
                </div>
              </div>
            </Link>
            {/*  */}
          </section>
        </div>
      </div>

      <div className="h-max flex pb-6 flex-col space-y-10 px-10 justify-center2 items-center2 bg-[#f6f8f7]">
        <div className="flex flex-row mx-auto w-full space-x-6 justify-center2 items-center">
          <div className="flex justify-between items-center w-full  px-4 py-4 rounded border border-gray-800 bg-white">
            <div>
              <nav
                aria-label="Pagination"
                className="flex items-center space-x-1 text-xs font-mabry text-gray-600"
              >
                <a href="#" className="p-1 rounded hover:bg-gray-100">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-4 w-4"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M15 19l-7-7 7-7"
                    />
                  </svg>
                </a>
                <a href="#" className="px-2 py-1 rounded hover:bg-gray-100">
                  {" "}
                  1{" "}
                </a>
                <a
                  href="#"
                  className="px-2 py-1 rounded bg-gray-200 text-gray-900 font-medium hover:bg-gray-100"
                >
                  {" "}
                  2{" "}
                </a>
                <a href="#" className="px-2 py-1 rounded hover:bg-gray-100">
                  {" "}
                  3{" "}
                </a>
                <a href="#" className="px-2 py-1 rounded hover:bg-gray-100">
                  {" "}
                  ...{" "}
                </a>
                <a href="#" className="px-2 py-1 rounded hover:bg-gray-100">
                  {" "}
                  9{" "}
                </a>
                <a href="#" className="p-1 rounded hover:bg-gray-100">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-4 w-4"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M9 5l7 7-7 7"
                    />
                  </svg>
                </a>
              </nav>
            </div>
            <div className="text-sm font-mabry">Showing 1-9 of 60825</div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}
