import React, { useEffect } from "react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import GoTop from "@/components/GoTop";

const events = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <GoTop />
      <div className="bg-[#f6f8f7] relative md:py-12 ">
        <article className="max-w-3xl mx-auto relative z-10 py-8 px-2 md:px-4 markdown">
          <div className="container bg-white mx-auto mt-12 p-4 md:p-6 rounded-xl shadow-lg">
            <div className="py-6 flex w-full md:w-2/3 font-mabrybold mx-auto">
              <div className="mx-auto">
                <div className="bg-mint mx-auto hover:bg-white border-2 border-gray-800 shadow text-black uppercase px-2 font-display font-mabryblack leading-tight text-3xl md:text-3xl tracking-tight l transform -rotate-2 md:-rotate-2">
                  Upcoming event
                </div>
              </div>
            </div>
            <div>
              <div className="flex space-x-1 my-4 py-2 px-4 bg-gray-900">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  dataSlot="icon"
                  className="w-6 h-6 text-white"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 0 1 2.25-2.25h13.5A2.25 2.25 0 0 1 21 7.5v11.25m-18 0A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75m-18 0v-7.5A2.25 2.25 0 0 1 5.25 9h13.5A2.25 2.25 0 0 1 21 11.25v7.5"
                  />
                </svg>

                <h2 className=" uppercase font-mabrybold  tracking-tight text-lg text-white font-light font-display">
                  May 2023
                </h2>
              </div>
              <div className=" columns-1 md:columns-2 lg:columns-3">
                <Link
                  href={"/events/event-one"}
                  className="relative z-10 mb-6 rounded-md bg-[#f4f2ef]  flex  overflow-hidden2 justify-center items-center cursor-zoom-in border-2 border-gray-900 shadow-menu"
                >
                  <div className="flex flex-col justify-center items-center w-16 text-white bg-slate-900 p-2">
                    <span className="text-sm font-mabry">Jul</span>
                    <span className="font-mabrybold text-lg">15</span>
                  </div>
                  <div className="flex-grow py-2 lg:py-4 md:py-4 px-4">
                    <p className="leading-tight md:leading-tight text-black font-mabryblack text-lg md:text-2xl lg:text-2xl">
                    Champs-Elysées Film Festival
                    </p>
                    <div className="font-mabry flex items-center space-x-1 text-gray-900">
                      <div>
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          strokeWidth={1.5}
                          stroke="currentColor"
                          dataSlot="icon"
                          className="w-5 h-5"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            d="M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"
                          />
                        </svg>
                      </div>
                      <span>6:30 pm - 10:30 pm</span>
                    </div>
                  </div>
                  <div className="absolute flex -bottom-3 z-30 right-3 px-3 py-0.5 rounded-lg bg-white shadow-menu border-2 border-gray-900">
                    <div>
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        strokeWidth={1.5}
                        stroke="currentColor"
                        dataSlot="icon"
                        className="w-4 h-4"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          d="M16.5 12a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0Zm0 0c0 1.657 1.007 3 2.25 3S21 13.657 21 12a9 9 0 1 0-2.636 6.364M16.5 12V8.25"
                        />
                      </svg>
                    </div>
                    <span className="text-xs font-mabrybold capitalize">
                      yokohama stadium
                    </span>
                  </div>
                </Link>
                <Link
                  href={"/events/event-one"}
                  className="relative z-10 mb-6 rounded-md bg-[#f4f2ef]  flex overflow-hidden2 justify-center items-center cursor-zoom-in border-2 border-gray-900 shadow-menu"
                >
                  <div className="flex flex-col justify-center items-center w-16 text-white bg-slate-900 p-2">
                    <span className="text-sm font-mabry">Jul</span>
                    <span className="font-mabrybold text-lg">15</span>
                  </div>
                  <div className="flex-grow py-2 lg:py-4 md:py-4 px-4">
                    <p className="leading-tight md:leading-tight text-black font-mabryblack text-lg md:text-2xl lg:text-2xl">
                      L’Amour et les Forêts
                    </p>
                    <div className="font-mabry flex items-center space-x-1 text-gray-900">
                      <div>
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          strokeWidth={1.5}
                          stroke="currentColor"
                          dataSlot="icon"
                          className="w-5 h-5"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            d="M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"
                          />
                        </svg>
                      </div>
                      <span>6:30 pm - 10:30 pm</span>
                    </div>
                  </div>
                  <div className="absolute flex -bottom-3 z-30 right-3 px-3 py-0.5 rounded-lg bg-white shadow-menu border-2 border-gray-900">
                    <div>
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        strokeWidth={1.5}
                        stroke="currentColor"
                        dataSlot="icon"
                        className="w-4 h-4"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          d="M16.5 12a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0Zm0 0c0 1.657 1.007 3 2.25 3S21 13.657 21 12a9 9 0 1 0-2.636 6.364M16.5 12V8.25"
                        />
                      </svg>
                    </div>
                    <span className="text-xs font-mabrybold capitalize">
                      yokohama stadium
                    </span>
                  </div>
                </Link>
                <Link
                  href={"/events/event-one"}
                  className="relative z-10 mb-6 rounded-md bg-[#f4f2ef]  flex  overflow-hidden2 justify-center items-center cursor-zoom-in border-2 border-gray-900 shadow-menu"
                >
                  <div className="flex flex-col justify-center items-center w-16 text-white bg-slate-900 p-2">
                    <span className="text-sm font-mabry">Jul</span>
                    <span className="font-mabrybold text-lg">15</span>
                  </div>
                  <div className="flex-grow py-2 lg:py-4 md:py-4 px-4">
                    <p className="leading-tight md:leading-tight text-black font-mabryblack text-lg md:text-2xl lg:text-2xl">
                    Mobile Apps with Svelte and Capacitor
                    </p>
                    <div className="font-mabry flex items-center space-x-1 text-gray-900">
                      <div>
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          strokeWidth={1.5}
                          stroke="currentColor"
                          dataSlot="icon"
                          className="w-5 h-5"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            d="M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"
                          />
                        </svg>
                      </div>
                      <span>6:30 pm - 10:30 pm</span>
                    </div>
                  </div>
                  <div className="absolute flex -bottom-3 z-30 right-3 px-3 py-0.5 rounded-lg bg-white shadow-menu border-2 border-gray-900">
                    <div>
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        strokeWidth={1.5}
                        stroke="currentColor"
                        dataSlot="icon"
                        className="w-4 h-4"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          d="M16.5 12a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0Zm0 0c0 1.657 1.007 3 2.25 3S21 13.657 21 12a9 9 0 1 0-2.636 6.364M16.5 12V8.25"
                        />
                      </svg>
                    </div>
                    <span className="text-xs font-mabrybold capitalize">
                      yokohama stadium
                    </span>
                  </div>
                </Link>
                <Link
                  href={"/events/event-one"}
                  className="relative z-10 mb-6 rounded-md bg-[#f4f2ef]  flex  overflow-hidden2 justify-center items-center cursor-zoom-in border-2 border-gray-900 shadow-menu"
                >
                  <div className="flex flex-col justify-center items-center w-16 text-white bg-slate-900 p-2">
                    <span className="text-sm font-mabry">Jul</span>
                    <span className="font-mabrybold text-lg">15</span>
                  </div>
                  <div className="flex-grow py-2 lg:py-4 md:py-4 px-4">
                    <p className="leading-tight md:leading-tight text-black font-mabryblack text-lg md:text-2xl lg:text-2xl">
                    Champs-Elysées Film Festival
                    </p>
                    <div className="font-mabry flex items-center space-x-1 text-gray-900">
                      <div>
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          strokeWidth={1.5}
                          stroke="currentColor"
                          dataSlot="icon"
                          className="w-5 h-5"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            d="M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"
                          />
                        </svg>
                      </div>
                      <span>6:30 pm - 10:30 pm</span>
                    </div>
                  </div>
                  <div className="absolute flex -bottom-3 z-30 right-3 px-3 py-0.5 rounded-lg bg-white shadow-menu border-2 border-gray-900">
                    <div>
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        strokeWidth={1.5}
                        stroke="currentColor"
                        dataSlot="icon"
                        className="w-4 h-4"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          d="M16.5 12a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0Zm0 0c0 1.657 1.007 3 2.25 3S21 13.657 21 12a9 9 0 1 0-2.636 6.364M16.5 12V8.25"
                        />
                      </svg>
                    </div>
                    <span className="text-xs font-mabrybold capitalize">
                      yokohama stadium
                    </span>
                  </div>
                </Link>
              </div>
            </div>
          </div>
        </article>
      </div>
      <Footer />
    </>
  );
};

export default events;
